const steps = [
  ['1｜最初の約10分：相手自身を知る','仕事・経験・日常から、その人が大切にしていることを一つ掴む。10分雑談すること自体が目的ではない。','「普段はどんなお仕事をされてるんです？」\n「その仕事を始めたきっかけは？」\n「やっていて良かったと思うのはどんな時です？」\n「お休みの日は何をされてます？」','途中で短く返す：\n「つまり、忙しさより、自分で時間を選べないことがしんどいんですね？」'],
  ['2｜一度まとめて「なぜ今」へ','人物理解を要約して認識を合わせ、今動いた直接のきっかけを聞く。','「一回ここまで整理してもいいですか？」\n「【事実】で、【価値観】を大切にしている。一方で【変えたいこと】がある、という理解で合っています？」','「今ちゃんと副業に動こうと思ったきっかけって何だったんです？」\n過去にも経験あり：「今また本格的にやろうと思ったのは、何か変化があったんですか？」'],
  ['3｜未来を映像化する','理想を、情景・感情・期限・直近目標まで本人の言葉で描く。','「その先で、どんな生活や働き方を作れたら理想です？」\n「その一日は朝からどんな感じです？」\n「どんな気持ちで過ごしてそうです？」\n「いつ頃までに近づきたいです？」','金額が出たら：「その金額があることで、生活の何が一番変わりそうです？」'],
  ['4｜未来から現在へ戻る','応募→返信→テスト→受注→継続のどこで止まるかを見る。','「その未来に早く近づくため、今どこで止まっているか一緒に見てもいいですか？」\n「副業を始めてどれくらいです？」\n「どんな案件へ何件くらい応募しています？」\n「返信・テスト・受注・継続はどんな状態です？」','時間・現在収入は必要な時だけ聞く。数字を埋めるより、止まる段階を見つける。'],
  ['5｜予定不調和：あるものと結果を並べる','目標・時間・行動・確認できた良い点があるのに結果へ届いていない事実を、本人と見る。','「一回、今あるものを整理してもいいですか？」\n「【目標】があり、週【時間】使えて、【行動】もされています。文章でも【良い点】はありました。」\n「それでも今は【段階】で止まっている。ご自身では何が止めていると思います？」','答えが出なければ：「企業さん側の視点から、一緒に整理してみてもいいですか？」'],
  ['6｜発注者目線で必要な材料を考える','PFを先に答えとして出さず、企業が安心して任せるための情報を本人に考えてもらう。','「自分がライターさんへ発注するなら、何が分かる人なら任せやすいです？」\n「今の応募文やプロフィールでは、それはどこまで伝わっています？」','「今は書けないというより、企業さんが判断できる材料が不足候補かもしれません。この見立てをどう感じます？」'],
  ['7｜課題認識を合わせてPFへ','本人が不足だと認めた時だけ、PFと実績が揃った後の変化を聞く。','「ここまでで、まず何を整えるのが優先だと感じます？」\n「企業さんに見せられるPFと実績が揃ったら、今より案件獲得は進みそうですか？」\n「今と比べて、何が変わりそうです？」','「その判断材料を一つにまとめたものが、ライター向けPFです。実際に一緒に見てみます？」'],
  ['8｜PFは説明→確認を小さく回す','本人の言葉へ戻す→一項目説明→どう役立つか本人へ返す。機能一覧を一気に読まない。','「最初に見て、どう感じます？」\n「【本人の経験】はどんな案件で強みになりそうです？」\n「実績がここに揃ったら、応募する感覚はどう変わりそうです？」','「つまり、○○さんの場合は【本人が感じた価値】が一番大きいんですね？」'],
  ['9｜支援を課題にだけ接続する','自作と支援を比較し、関心がある時だけ内容説明の許可を取る。','「自分で一から作る方法と、必要なところを支援してもらう方法なら、どちらが進めやすそうです？」\n「今のお悩みに関係する内容だけ、具体的に紹介してもいいですか？」','説明後：「どの部分が一番役立ちそうでした？」\n「逆に、まだ足りないことや不安はあります？」\n必要性・自作難度・関心を確認してから意思を聞く。'],
];
const cards = steps.map(([title,goal,talk,note])=>`<details><summary>${title}</summary><div class="body"><h3>ここでのゴール</h3><p>${goal}</p><h3>そのまま使える会話</h3><p class="talk">${talk.replaceAll('\n','<br>')}</p><p class="note">${note.replaceAll('\n','<br>')}</p></div></details>`).join('');
export const conversationFlowPage = `<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>一本の会話｜緒方 Sales Script</title><style>*{box-sizing:border-box}body{margin:0;background:#f6f4ee;color:#252a25;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}header{position:sticky;top:0;z-index:3;background:#fffdf8ef;backdrop-filter:blur(10px);padding:12px 16px;border-bottom:1px solid #ddd8ca;display:flex;gap:16px;align-items:center;overflow:auto;white-space:nowrap}a{color:#315d49;text-decoration:none}nav{display:flex;gap:14px}main{max-width:900px;margin:auto;padding:28px 16px 80px}h1{font-size:clamp(30px,7vw,54px);margin:0 0 8px}.lead{font-size:18px;line-height:1.8}.spine{padding:16px 18px;background:#e5f0e8;border:1px solid #bfd2c5;border-radius:16px;line-height:1.8;margin:20px 0}details{background:#fff;border:1px solid #dedbd0;border-radius:16px;margin:12px 0;overflow:hidden}summary{cursor:pointer;font-weight:800;font-size:18px;padding:18px;line-height:1.5}.body{padding:0 18px 20px;border-top:1px solid #eee9dc}.body h3{font-size:13px;color:#66736c;margin:18px 0 6px}.body p{line-height:1.8;margin:6px 0}.talk{background:#f7f8f5;padding:14px;border-radius:12px}.note{background:#fff5dc;padding:12px;border-radius:12px;margin-top:12px!important}@media(max-width:600px){header{font-size:14px}main{padding-top:22px}summary{font-size:16px;padding:16px}}</style></head><body><header><a href="/today">← WorkOS</a><nav><a href="/sales-script">全文台本</a><a href="/sales-script/flow"><strong>一本の会話</strong></a><a href="/sales-script/deep-dive">深掘り</a><a href="/sales-script/questions">答え問題集</a></nav></header><main><h1>一本の会話</h1><p class="lead">ラポールから予定不調和、ポートフォリオの必要性、提案までを迷わずつなぐ実戦用の背骨です。</p><div class="spine"><b>相手を知る → 小さく認識合わせ → なぜ今 → 未来を映像化 → 現在 → 予定不調和 → 発注者目線 → 課題合意 → 対話でPF → 必要な支援だけ提案</b><br>全部の質問は聞きません。相手の言葉に反応し、意味が分かれば次へ進みます。</div>${cards}</main></body></html>`;
