type Phase = { name:string; goal:string; must:string; base:string; triggers:string; deepen:string; align:string; ready:string; bridge:string; talk:string };
type Trigger = { category:string; trigger:string; want:string; q1:string; q2:string; q3:string; align:string; reuse:string };

const phases: Phase[] = [
  {name:'1｜最初の約10分：相手自身を知る',goal:'仕事・経験・日常から、その人が大切にしていることを一つ理解する。',must:'本人が自然に話す事実、感情が動く話、繰り返す言葉。',base:'「普段はどんなお仕事をされてるんです？」',triggers:'楽しそうに話す／繰り返す／時間・挑戦・我慢・家族を本人から話す。',deepen:'「始めたきっかけは？」→「続けている理由は？」→「何を大切にしています？」',align:'「つまり【本人の言葉】を大切にされているんですね？」',ready:'仕事内容だけでなく、その人にとっての意味が一つ分かった。',bridge:'「一回ここまで整理してもいいですか？」',talk:'「10分雑談するのではなく、この人が何を大切にしているかを一つ知る。」'},
  {name:'2｜小さく認識を合わせ「なぜ今」へ',goal:'前半を要約し、副業を今始めた直接のきっかけを理解する。',must:'今変えたいこと・きっかけ・過去ではなく今動く理由。',base:'「今ちゃんと副業に動こうと思ったきっかけって何だったんです？」',triggers:'前にも挑戦／最近の変化／収入／時間／働き方／将来。',deepen:'「何が変わった？」→「なぜ今？」→「変わったら何が違う？」',align:'「【きっかけ】があって、今のうちに【変えたいこと】を変えようと動かれたんですね？」',ready:'人物理解と副業の動機を一文で本人へ返し、確認できた。',bridge:'「その先で、どんな生活や働き方を作れたら理想です？」',talk:'「認識合わせは10分後だけでなく、意味が見えた都度短く返す。」'},
  {name:'3｜未来を映像化する',goal:'本人の未来を情景・感情・期限・直近目標まで具体化する。',must:'理想の一日・得たい感情・期限・最初の目標・金額の意味。',base:'「その先で、どんな生活や働き方を作れたら理想です？」',triggers:'自由／安定／月5万円／旅行／家族／退職／挑戦。',deepen:'「一日は？」→「どんな気持ち？」→「いつまで？」→「最初の一歩は？」',align:'「【期限】までに【情景】で【感情】を得たい。まず【直近目標】を作りたいんですね？」',ready:'本人の言葉だけで未来と直近目標を説明できる。',bridge:'「その未来に早く近づくため、今どこで止まっているか一緒に見てもいいですか？」',talk:'「金額が出たら、“その金額で生活の何が変わる？”まで聞く。」'},
  {name:'4｜未来から現在へ戻る',goal:'応募から継続までのどこで止まっているかを事実で把握する。',must:'開始時期・応募・返信・テスト・受注・継続・時間・現在収入。',base:'「実際に動いてみて、今はどんな感じです？」',triggers:'返信がない／テストで落ちる／単発／低単価／時間不足。',deepen:'「何件応募？」→「どこまで進む？」→「直近はどこで止まった？」',align:'「今は【行動】に対して【結果】で、主に【段階】で止まっている状態ですね？」',ready:'理想、現在、止まる段階の3点が分かった。',bridge:'「一回、今すでにあるものも整理していいですか？」',talk:'「数字を全部埋めるより、どこで止まるかを見つける。」'},
  {name:'5｜予定不調和：あるものと結果を並べる',goal:'持っている力と結果の不一致を見せ、本人と原因を考える。',must:'確認済みの目標・時間・行動・良い点と、未達の事実。',base:'「これだけ動ける材料がある中で、まだ結果につながっていないのは何が原因だと思います？」',triggers:'目標も時間も行動もある／本人が理由を説明できない。',deepen:'「そう思うきっかけは？」→「どこで止まる？」→「何が変われば進む？」',align:'「頑張っていないのではなく、【止まる段階】で何かが伝わっていない可能性があるんですね？」',ready:'営業側が原因を決めず、本人の仮説または“分からない”を確認した。',bridge:'「企業さん側の視点から、一緒に整理してみてもいいですか？」',talk:'「予定不調和は驚かせる演出ではなく、“あるのに届かない”を共同発見する。」'},
  {name:'6｜発注者目線で必要な材料を考える',goal:'企業が安心して任せるための判断材料を本人に考えてもらう。',must:'実績・得意分野・人柄・対応力・今見せている資料。',base:'「自分が発注するなら、何が分かる人なら任せやすいです？」',triggers:'実績／強み／人柄／最後まで対応／専門性。',deepen:'「今どこで見せてる？」→「企業は判断できる？」→「一か所なら何が変わる？」',align:'「今は書けないより、任せられる根拠を伝える材料が不足候補なんですね？」',ready:'本人が課題候補に同意、または別の原因へ修正した。',bridge:'「では、必要な状態をもう一度短く整理していいですか？」',talk:'「PFありきにせず、応募文・品質・応募先が原因ならそちらを優先する。」'},
  {name:'7｜課題認識を合わせる',goal:'すでにあるものと不足を本人と合意し、必要な状態を言語化する。',must:'本人が認めたボトルネック・解決後に変わること。',base:'「ここまでで、まず何を整えるのが優先だと感じます？」',triggers:'見せるもの／実績／FB／相談／応募先／記事品質。',deepen:'「それがあると何が変わる？」→「自分でできる？」→「支援が必要なのは？」',align:'「まず【本人が認めた不足】を整えるのが優先という認識ですね？」',ready:'本人が課題と必要な状態を自分の言葉で説明できた。',bridge:'「実際にどう見えるのか、一緒に見てみます？」',talk:'「PFと実績が揃ったら、今より何が変わりそうです？」'},
  {name:'8｜対話でPFを見る',goal:'説明を聞かせず、本人が自分への価値を言語化する。',must:'第一印象・本人なら載せる経験・実績が揃った時の変化。',base:'「最初に見て、どう感じます？」',triggers:'経歴／強み／実績／得意分野／条件／問い合わせ。',deepen:'「〇〇さんなら何を書く？」→「経験は強みになる？」→「実績が載ったら？」',align:'「今より【本人が言った変化】がありそうと感じたんですね？」',ready:'本人がPFの役割と自分に必要な箇所を説明できた。',bridge:'「こういうものを一から自分で作るとしたら、どうです？」',talk:'「一項目説明するたび、“何が変わりそう？”と相手へ返す。」'},
  {name:'9｜支援を課題にだけ接続する',goal:'機能一覧ではなく、本人の不足に関係する支援だけ説明する。',must:'必要な支援・自作範囲・未解消の不安。',base:'「自分で作る方法と、必要なところを支援してもらう方法ならどちらが進めやすそうです？」',triggers:'自作は難しい／実績が欲しい／添削が欲しい／相談したい。',deepen:'「どこが難しい？」→「何を手伝ってほしい？」→「まだ何が不安？」',align:'「【本人の課題】に対して、【本人が選んだ支援】が役立ちそうという理解ですね？」',ready:'必要性・自作の難しさ・支援への関心を確認できた。',bridge:'「関係する内容だけ、具体的に紹介してもいいですか？」',talk:'「本人の言葉へ戻す→一つ説明→どう役立つか本人に返してもらう。」'},
  {name:'10｜自然に次の行動へ',goal:'内容を理解した本人が、進む・保留・見送るを自由に選べるようにする。',must:'役立つ部分・足りない部分・正式条件・本人の意思。',base:'「どの部分が一番役立ちそうでした？」',triggers:'作りたい／検討したい／不安／自分でやりたい。',deepen:'「何が足りない？」→「内容で不明点は？」→「内容として進めたい？」',align:'「内容としては【本人の意思】で、残る確認は【不安】ですね？」',ready:'疑問が整理され、本人が意思を選べる。',bridge:'「内容が合いそうなら、正式な提供範囲と費用を確認します？」',talk:'「価値を営業側だけで断言せず、本人が役立つ理由を言える状態にする。」'},
];

const triggers: Trigger[] = [
  {category:'仕事・働き方',trigger:'今の仕事が忙しい',want:'実際の稼働・副業時間・働き方を変えたい度合い',q1:'結構忙しいんですね。普段どれくらい働いてるんです？',q2:'その中で、副業に無理なく使えそうな時間はどれくらいあります？',q3:'その生活を続けたいです？それとも働き方自体も変えたいです？',align:'本業をすぐ辞めたいというより、まず限られた時間で別の収入を作りたい感じですか？',reuse:'後半で「週【時間】を守りながら進める方法」として回収する。'},
  {category:'仕事・働き方',trigger:'仕事に空き時間がある',want:'使える時間・ライティングを始めた動機',q1:'どれくらい空くんです？',q2:'その時間は今、何をしてることが多いです？',q3:'その時間を収入につなげられたら、何が変わりそうです？',align:'空き時間を活かしたいことが、ライティングを始めた理由として大きいんですね？',reuse:'提案時に「今ある時間を案件経験へ変える土台」として回収する。'},
  {category:'仕事・働き方',trigger:'今の仕事を辞めたい',want:'退職したい背景・期限・理想の働き方',q1:'辞めたいと思う一番大きな理由は何です？',q2:'それはいつ頃から感じています？',q3:'逆に、理想の働き方はどんな感じです？',align:'収入だけではなく、【本人の言葉】という働き方そのものを変えたいんですね？',reuse:'退職を煽らず、本人の期限と安全な移行条件へ戻す。'},
  {category:'金銭',trigger:'月5万円欲しい',want:'金額の根拠・使い道・安定性',q1:'5万円って、何か理由がある金額なんです？',q2:'その5万円は何に使いたいです？',q3:'毎月入ったら、今と何が一番変わりそうです？',align:'単発で5万円より、毎月安定して【使い道】に使える状態が理想なんですね？',reuse:'価格ではなく「本人が作りたい生活」を後半で回収する。'},
  {category:'金銭',trigger:'もっと収入を増やしたい',want:'必要額・現在我慢していること・期限',q1:'今の収入にプラスして、どれくらいあると理想です？',q2:'その金額があると何ができるようになります？',q3:'それはいつ頃までには変えたいです？',align:'収入額そのものより、【できるようになりたいこと】を実現したいんですね？',reuse:'目標額・期限・用途を一文で返す。'},
  {category:'生活',trigger:'一人暮らし・実家・同居',want:'生活環境・時間の裁量・無理のない稼働',q1:'今はどなたと暮らしてるんです？話せる範囲で大丈夫です。',q2:'仕事後の時間は、自分で使いやすい感じです？',q3:'平日と休日で、副業に無理なく使えるのはどれくらいです？',align:'今の生活を崩さず、週【時間】くらいで進めたい感じなんですね？',reuse:'家族構成を購入理由にせず、稼働計画だけへ使う。'},
  {category:'生活',trigger:'趣味・推し活・旅行',want:'理想の生活・支出の意味・収入を増やす理由',q1:'それ、どれくらいの頻度でされるんです？',q2:'今は時間や金額を気にして我慢することもあります？',q3:'副業収入が増えたら、どう楽しめるようになりたいです？',align:'【趣味】を無理なく楽しめる余裕を作りたいことも、収入を増やす理由なんですね？',reuse:'後半で本人が話した楽しみとして短く回収。商品購入へ無理につなげない。'},
  {category:'家族・将来',trigger:'結婚したい・家庭を持ちたい',want:'本人の期限・理想の生活・働き方との関係',q1:'結婚後は、どんな生活が理想です？',q2:'何歳頃までには、というイメージはあります？',q3:'その生活を考えた時、今の収入や働き方で気になることはあります？',align:'【期限】頃までに、【本人の理想】を作れる働き方・収入に近づきたいんですね？',reuse:'不安を煽らず、本人が話した期限から逆算する時だけ使う。'},
  {category:'家族・将来',trigger:'子どもが欲しい',want:'将来の期限・働き方・必要収入・準備の重要度',q1:'その頃は、どんな働き方をしていたいです？',q2:'何歳頃までには、というイメージがあります？',q3:'その生活なら、収入面はどれくらいあると安心できそうです？',align:'今から副業収入の土台を作りたい理由にも、将来の家庭像がつながっているんですね？',reuse:'本人が自分から話した場合だけ、未来と現在の行動をつなぐ。'},
  {category:'現在の悩み',trigger:'案件が取れない',want:'停止段階・本人の原因仮説・企業側からの見え方',q1:'今どれくらい応募して、どこまで進んでいます？',q2:'ご自身では、取れていない理由を何だと思います？',q3:'企業側は、強みや実績を今どこで確認できます？',align:'主に【停止段階】で止まり、【見せる材料等】が課題候補という認識で合っています？',reuse:'本人が合意してからPF・応募文・品質の該当ルートへ進む。'},
  {category:'現在の悩み',trigger:'単価が低い',want:'現単価・必要件数・継続可能性・単価を上げる根拠',q1:'今は1案件どれくらいです？',q2:'そのペースだと目標金額まで何件必要になります？',q3:'その件数を毎月続けるのは現実的そうです？',align:'件数だけ増やすより、単価を上げられる根拠も作る必要がありそうですね？',reuse:'専門性・実績・品質・進行力のどれを証拠にするかへ進む。'},
  {category:'現在の悩み',trigger:'何をしたらいいか分からない',want:'不明点の範囲・試したこと・停止箇所',q1:'案件の取り方、スキル、進め方全体だと、どこが一番分かりません？',q2:'今まで何か試したことはあります？',q3:'試してみて、どこで止まりました？',align:'全部が分からないというより、まず【停止箇所】が見えれば進めそうなんですね？',reuse:'最初の一手を1つだけ合意する。'},
  {category:'理想',trigger:'月5〜10万円稼ぎたい',want:'本人にとって意味のある額・用途・理想の案件状態・期限',q1:'5万円と10万円なら、どこまでいくと「変わった」と感じます？',q2:'その金額を何に使いたいです？',q3:'毎回応募するのと、継続依頼が来る状態ならどちらが理想です？',align:'【期限】までに月【額】が安定して入り、【案件状態・使い道】ができるのが理想なんですね？',reuse:'後半で「PFを持つこと」ではなく、この案件状態へ近づく土台として回収する。'},
  {category:'理想',trigger:'自由になりたい',want:'抽象語の定義・理想の一日・現在との差',q1:'〇〇さんにとって自由って、具体的にどんな状態です？',q2:'時間・場所・収入だと、どれが一番近いです？',q3:'理想の平日は、朝からどんな一日です？',align:'自由とは、【本人の具体的な状態】で過ごせることなんですね？',reuse:'抽象語をそのまま提案文に使わず、具体化した生活を返す。'},
  {category:'なぜ今',trigger:'今、副業を始めたい',want:'きっかけ・本人の緊急度・期限',q1:'これって、なんで今始めようと思ったんです？',q2:'半年前や1年前ではなく、今だった理由はあります？',q3:'今やらなかったら、ご自身ではどうなりそうだと思います？',align:'【きっかけ】があって、【期限】までには変えたいという温度感なんですね？',reuse:'危機感を作らず、本人が示した緊急度だけを後半で使う。'},
  {category:'意思決定',trigger:'以前サービスを見たがやらなかった',want:'見送った理由・選ぶ条件・重視価値',q1:'その時は、何が引っかかってやらなかったんです？',q2:'逆に、どういう条件ならやってみようと思えました？',q3:'サポート・実績・金額・自分との相性なら、何が一番大きいです？',align:'選ぶ時に一番大事なのは【本人が選んだ基準】なんですね？',reuse:'後半はその基準に関係する事実だけ説明し、誘導に使わない。'},
  {category:'案件獲得',trigger:'ポートフォリオがない・実績がない',want:'企業へ見せる材料・本人が感じる必要性・自作可能性',q1:'応募時に、経歴・強み・記事は何で見せています？',q2:'企業側からすると、今どこまで判断できそうです？',q3:'それが一か所で見えたら、何が変わりそうです？',align:'今は書けないのではなく、任せられる根拠を見せる材料が不足候補なんですね？',reuse:'本人の合意後だけPF実物へ進む。'},
  {category:'認識合わせ',trigger:'話が広がった・情報が揃った',want:'聞いた事実・本人の意味・理想・ギャップの一致',q1:'一回ここまで整理してもいいですか？',q2:'今は【現状】で、【きっかけ】から副業を始めたんですね。',q3:'理想は【期限】までに【具体的な状態】で、今との間に【差】がある。',align:'一番変えたいのは【本人の課題】という認識で合っています？',reuse:'違うと言われたら直す。YESを取るために誘導しない。'},
];

const esc=(value:string)=>value.replace(/[&<>"']/g,(char)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!));
const phaseCards=phases.map((p)=>`<details class="phase"><summary>${esc(p.name)}<span>${esc(p.goal)}</span></summary><div class="phase-body">${[['フェーズのゴール',p.goal],['必須で理解したい情報',p.must],['基本質問',p.base],['深掘りトリガー',p.triggers],['縦に深掘る質問候補',p.deepen],['認識合わせ',p.align],['次へ進んでいい条件',p.ready],['次フェーズへのブリッジ',p.bridge],['実際のトーク例',p.talk]].map(([k,v])=>`<section><b>${esc(k)}</b><p>${esc(v)}</p></section>`).join('')}</div></details>`).join('');

export const deepDivePage=`<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>深掘りカンペ｜緒方 Sales Script</title><style>
:root{--bg:#f6f5f0;--card:#fff;--ink:#21382f;--muted:#65736c;--line:#d5ded7;--green:#21634d;--soft:#edf5ee;--gold:#8a6817;--goldsoft:#fbf6e7}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:16px/1.72 "Hiragino Sans","Yu Gothic UI",Meiryo,sans-serif}header,main{max-width:1080px;margin:auto;padding:15px 20px}header,nav,.filters{display:flex;gap:8px;align-items:center;flex-wrap:wrap}a{color:var(--green)}nav a{background:#fff;border:1px solid var(--line);padding:7px 10px;border-radius:10px;text-decoration:none}h1{font-size:29px;margin:12px 0 3px}.lead{margin:0;color:var(--muted)}.rule{background:var(--soft);border:1px solid #cfe0d3;border-radius:15px;padding:14px 16px;margin:14px 0}.rule b{color:var(--green)}.rule p{margin:4px 0}.internal{font-size:14px;color:var(--muted)}h2{font-size:22px;margin:25px 0 9px}.phase,.trigger{background:var(--card);border:1px solid var(--line);border-radius:14px;margin:8px 0;overflow:hidden}.phase summary,.trigger summary{cursor:pointer;padding:14px 16px;font-weight:800;list-style:none}.phase summary span,.trigger summary span{display:block;font-weight:400;color:var(--muted);font-size:13px}.phase-body,.trigger-body{border-top:1px solid var(--line);padding:11px 15px 15px;display:grid;gap:8px}.phase-body section,.step{border-left:3px solid var(--line);padding:5px 10px}.phase-body b,.label{font-size:12px;color:var(--green);display:block}.phase-body p,.step p{margin:2px 0}.tools{position:sticky;top:0;z-index:5;background:#f6f5f0ec;padding:10px 0;border-bottom:1px solid var(--line)}input{width:100%;padding:12px 14px;border:1px solid var(--line);border-radius:12px;font:inherit}.filters{overflow:auto;padding-top:8px;flex-wrap:nowrap}.filter{white-space:nowrap;border:1px solid var(--line);border-radius:999px;background:#fff;padding:7px 10px}.filter.active{background:var(--green);color:#fff}.want{background:var(--goldsoft);border:1px solid #eadcae;border-radius:11px;padding:9px 11px}.want b{color:var(--gold);display:block;font-size:12px}.chain{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.step{border:1px solid var(--line);border-radius:11px}.align{background:var(--soft);border-color:#cfe0d3}.reuse{color:var(--muted);font-size:14px}.empty{padding:25px;color:var(--muted)}@media(max-width:720px){header,main{padding:12px}h1{font-size:24px}.chain{grid-template-columns:1fr}.phase summary,.trigger summary{padding:13px}.phase-body,.trigger-body{padding:10px 12px 13px}}
</style></head><body><header><a href="/today">← WorkOS</a><nav><a href="/sales-script">全文台本</a><a href="/sales-script/deep-dive"><strong>深掘りカンペ</strong></a><a href="/sales-script/questions">答え問題集</a></nav></header><main><h1>深掘りカンペ</h1><p class="lead">相手の一語を拾い、背景・感情・価値観・重要度まで縦に理解するための地図です。</p><section class="rule"><b>全部は聞かない</b><p>相手の回答 → 復唱 → 意味を確認 → 必要ならあと1〜2問 → 認識合わせ。具体的な場面・本人にとっての意味・感情が分かれば次へ。</p><p class="internal">内部チェック：この人の「現在」と「副業で実現したい近未来」を第三者へ説明できるか。5W1Hは不足確認にだけ使い、質問表として読み上げない。</p></section><h2>商談の中心線と進行条件</h2>${phaseCards}<h2>言葉から引く縦深掘り</h2><div class="tools"><input id="search" type="search" placeholder="相手の言葉で検索：忙しい、5万円、家族、案件が取れない…"><div class="filters" id="filters"></div></div><p id="count"></p><div id="cards"></div></main><script type="application/json" id="data">${JSON.stringify(triggers).replace(/</g,'\\u003c')}</script><script>
const data=JSON.parse(document.getElementById('data').textContent),esc=s=>s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));let active='すべて';const cats=['すべて',...new Set(data.map(x=>x.category))];const filters=document.getElementById('filters');filters.innerHTML=cats.map((c,i)=>'<button class="filter '+(i?'':'active')+'" data-cat="'+esc(c)+'">'+esc(c)+'</button>').join('');function draw(){const q=document.getElementById('search').value.trim().toLowerCase();const hits=data.filter(x=>(active==='すべて'||x.category===active)&&JSON.stringify(x).toLowerCase().includes(q));document.getElementById('count').textContent=hits.length+'件を表示';document.getElementById('cards').innerHTML=hits.length?hits.map(x=>'<details class="trigger" '+(q?'open':'')+'><summary>'+esc(x.trigger)+'<span>'+esc(x.category)+'</span></summary><div class="trigger-body"><div class="want"><b>この質問で知りたいこと</b>'+esc(x.want)+'</div><div class="chain"><div class="step"><span class="label">1段目</span><p>「'+esc(x.q1)+'」</p></div><div class="step"><span class="label">2段目</span><p>「'+esc(x.q2)+'」</p></div><div class="step"><span class="label">3段目</span><p>「'+esc(x.q3)+'」</p></div></div><div class="step align"><span class="label">最後の認識合わせ</span><p>「'+esc(x.align)+'」</p></div><div class="reuse"><b>後半での回収：</b>'+esc(x.reuse)+'</div></div></details>').join(''):'<p class="empty">該当するカードがありません。</p>'}filters.onclick=e=>{const b=e.target.closest('button');if(!b)return;active=b.dataset.cat;filters.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));draw()};document.getElementById('search').oninput=draw;draw();
</script></body></html>`;
