import { latestSugiyamaMarkdown } from './sugiyama-latest';

const start = latestSugiyamaMarkdown.indexOf('## 21A｜課題別・質問と解説の問題集');
const endCandidates = [latestSugiyamaMarkdown.indexOf('\n# 22｜PFへ', start), latestSugiyamaMarkdown.indexOf('\n## 22｜PFへ', start)].filter((value) => value > start);
const end = endCandidates.length ? Math.min(...endCandidates) : -1;
const questionBank = start >= 0 && end > start ? latestSugiyamaMarkdown.slice(start, end).trim() : '問題集を読み込めませんでした。';

export const questionBankPage = `<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f6f5f0"><title>課題別・ポートフォリオ説明問題集｜緒方 Sales Script</title><style>
:root{--bg:#f6f5f0;--card:#fff;--ink:#233930;--muted:#5c6d64;--line:#d7dfd8;--accent:#23634d}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:17px/1.85 "Hiragino Sans","Yu Gothic UI",Meiryo,sans-serif}header,main{max-width:860px;margin:auto;padding:20px}header{display:flex;gap:12px;flex-wrap:wrap;align-items:center}a{color:var(--accent)}nav{display:flex;gap:10px;flex-wrap:wrap}nav a{padding:8px 12px;border:1px solid var(--line);border-radius:12px;background:var(--card);text-decoration:none}h1{font-size:30px;line-height:1.4;margin:16px 0 8px}p{white-space:pre-wrap}.lead{color:var(--muted)}input{width:100%;padding:14px 16px;border:1px solid var(--line);border-radius:14px;font:inherit;margin:18px 0;background:var(--card)}.card{background:var(--card);border:1px solid var(--line);border-radius:20px;padding:22px;margin:16px 0}.card h2{font-size:21px;margin:0 0 14px}.card h3{font-size:15px;color:var(--accent);margin:20px 0 6px}.card blockquote{margin:10px 0;padding:8px 14px;border-left:4px solid var(--accent);background:#edf5ee;border-radius:0 12px 12px 0}.empty{color:var(--muted)}@media(max-width:640px){header,main{padding:16px}h1{font-size:26px}.card{padding:18px}}
</style></head><body><header><a href="/today">← WorkOS</a><nav><a href="/sales-script">全文台本</a><a aria-current="page" href="/sales-script/questions"><strong>課題別問題集</strong></a><a href="/sales-script?edition=mogi">茂木さん版</a></nav></header><main><h1>課題別・ポートフォリオ説明問題集</h1><p class="lead">お客さんの言葉から探し、質問 → 本人との課題認識 → 必要性の説明 → 相手へ返す、の順で練習します。上から全部読む必要はありません。</p><input id="search" type="search" placeholder="例：AI、実績、単価、返信、フィードバック" aria-label="問題を検索"><div id="cards"></div></main><script type="application/json" id="bank">${JSON.stringify(questionBank).replace(/</g, '\\u003c')}</script><script>
const raw=JSON.parse(document.getElementById('bank').textContent);const esc=s=>s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));const parts=raw.split(/^### 問題/m).slice(1).map(x=>'### 問題'+x.trim());function renderOne(md){const lines=md.split(/\r?\n/);let html='',quote=[];const flush=()=>{if(quote.length){html+='<blockquote>'+quote.map(x=>esc(x.replace(/^> ?/,''))).join('<br>')+'</blockquote>';quote=[]}};for(const line of lines){if(line.startsWith('>')){quote.push(line);continue}flush();if(/^### /.test(line))html+='<h2>'+esc(line.slice(4))+'</h2>';else if(/^\*\*.+\*\*$/.test(line))html+='<h3>'+esc(line.replace(/\*\*/g,''))+'</h3>';else if(line.trim())html+='<p>'+esc(line.replace(/\*\*/g,''))+'</p>'}flush();return html}function draw(q=''){const root=document.getElementById('cards');const hits=parts.filter(x=>x.toLowerCase().includes(q.toLowerCase()));root.innerHTML=hits.length?hits.map(x=>'<article class="card">'+renderOne(x)+'</article>').join(''):'<p class="empty">該当する問題がありません。</p>'}document.getElementById('search').addEventListener('input',e=>draw(e.target.value.trim()));draw();
</script></body></html>`;
