const groups = [
  { title: '信頼・継続', when: '継続依頼や長い本業経験が出た時', tags: '信頼 継続 誠意 強み', say: ['継続してお仕事をお願いされるって、「この人にまた任せたい」と思ってもらえているからだと思うんですよね。'], ask: ['ご自身では、どんなところを評価して継続してもらえていると思います？', '納期、丁寧さ、意図の理解、修正対応だと、どれが近そうです？'], note: '褒めて終わらず、本人が再現できる強みを言葉にしてもらう。' },
  { title: '本業を強みに変える', when: '本業・経歴・好きなことを聞いた後', tags: '本業 経験 専門性 漫画 半導体 動画', say: ['【本業】をされてきたからこそ分かる現場の感覚って、調べただけでは書けない強みですよね。', '作品や文章を見た時に「この言葉はこういう人に響きそう」と考える感覚も、ライティングで活かせそうですよね。'], ask: ['その経験は、どんなテーマの記事なら一番活かせそうです？', 'ご自身では普通だと思っているけど、他の人にはない経験ってあります？'], note: '営業側で適性を断定せず、本人の具体的な経験へ戻す。' },
  { title: '二本の収入の柱', when: '本業を辞めずに副業を育てたい時', tags: '本業 副業 二本柱 生活 未来', say: ['今のお仕事を安定させながら、その経験をライティングにも活かして、収入の柱を二つにする考え方もありそうですね。'], ask: ['二つの柱で収入を作れるようになったら、今の生活はどう変わりそうです？'], note: '本業を捨てる前提にしない。本人が望む働き方を確認する。' },
  { title: 'AI・学習を聞く', when: 'AIを使っている・学んでいると言われた時', tags: 'AI 学習 スクール スキル', say: [], ask: ['AIは、アイデア出し・構成・下書き・推敲だと、どこで使っています？', 'AIから出たものに、ご自身の経験や判断を足している部分はあります？', '今学んでいる中で、一番伸ばしたいのはどこです？'], note: 'スクール名や金額は、支援の重複確認に必要な時だけ聞く。' },
  { title: '目標額から現在地へ', when: '副業収入の目標が出た時', tags: '目標 金額 期限 現在地', say: [], ask: ['最終的には月どれくらい作れたら理想です？', 'まず直近だと、月いくら作れたら一歩進んだ感じがします？', 'その金額があると、生活の何が変わりそうです？', '今の案件単価だと、その金額には月何件くらい必要になりそうです？'], note: '金額は煽る材料ではなく、必要件数と使える時間を一緒に考えるために聞く。' },
  { title: '応募状況を数字で聞く', when: 'クラウドワークスや応募の話が出た時', tags: 'クラウドワークス 応募 返信 テスト 受注 継続 収入 時間', say: [], ask: ['始めてどれくらいで、今まで何件くらい応募しました？', 'そのうち返信、テスト、受注、継続はそれぞれ何件でした？', 'アンケートと記事作成は、それぞれどれくらいあります？', '全部でどれくらいの収入になって、時間はどれくらい使いました？'], note: '実数が揃う前に「低単価が原因」「PFが原因」と決めない。' },
  { title: '「慣れてから」を深掘る', when: '低単価案件で慣れてからと言われた時', tags: '慣れ 低単価 100件 基準 企業案件', say: ['慣れること自体は大事だと思います。'], ask: ['ちなみに、「慣れた」って何件やったら慣れたことになりそうです？', '10件、100件、期間、誰かから合格をもらうこと。この中だと何が基準になりそうです？', '低単価案件を100件と、企業案件を納期・修正まで1件やり切るのでは、次の判断材料として何が違いそうです？'], note: '低単価経験を否定せず、量より「何を経験できるか」へ視点を移す。' },
  { title: '企業・指名案件へ', when: '単価を上げたい・企業案件を取りたい時', tags: '単価 企業 指名 オファー 1万円 2円', say: ['多数の人から量を集めたい案件は、同じ条件で比較されやすく、価格競争になりやすいです。', '一方で、企業さんから「○○さんにこの記事を書いてほしい」と声がかかると、専門性や実績、信頼を含めて選ばれるので、単価を上げやすい形になります。'], ask: ['企業さんから声がかかって、その中から合う案件を選べる状態は理想に近いです？', '「○○さんに頼みたい」と思ってもらうには、何が見える必要があると思います？'], note: '文字単価2円・1記事1万円は目標例。案件条件で変わるため固定相場として言わない。' },
  { title: '問題提起を本人へ返す', when: '強み・時間・行動があるのに結果が出ていない時', tags: '問題提起 ボトルネック 原因 整理', say: ['一回整理してもいいですか？', '【強み】があって、【使える時間】もあって、実際に【行動】もされています。文章でも【確認できた良い点】があります。', 'それでも今は【止まっている段階】で止まっている。'], ask: ['○○さんご自身では、何が足りないと思います？', '企業さん側の目線から、一緒に考えてみてもいいですか？'], note: '「なんで取れないんでしょうね」だけで詰めず、確認できた事実を先に並べる。' },
  { title: '発注者目線へ切り替える', when: '原因が本人にも分からない時', tags: '企業 発注者 信頼 人柄 最後まで', say: ['そうですよね。企業さんも文章だけではなく、【相手が挙げた情報】を見て、「この人に任せて大丈夫か」を判断します。'], ask: ['もし○○さんがライターさんへお願いする側なら、どんなことが分かる人に任せたいです？', '今のプロフィールや応募文で、それはどこまで伝わっています？'], note: '先にPFと言わず、本人が発注者なら何を見るかを考えてもらう。' },
  { title: 'PFを履歴書＋受け皿で説明', when: 'PFの役割を説明する時', tags: 'ポートフォリオ 履歴書 名刺 差別化 問い合わせ', say: ['ポートフォリオは企業さんから見ると、Web上の履歴書に近いです。', 'ただ、経歴を置くだけではなく、強み・実績・人柄・対応条件まで見せて、「この人にお願いしたい」と思った企業さんが連絡できる受け皿になります。', '共通プロフィールだけでは見えにくい、○○さん固有の経験や仕事への向き合い方まで伝えられます。'], ask: ['PFと実績が揃ったら、企業さんは今より何を判断しやすくなりそうです？'], note: '「PFがないと仕事が来ない」と断定しない。応募文や品質など他の要因もある。' },
  { title: '自作・デザインの難しさ', when: 'PFを見せ終わった後', tags: '自作 デザイン 構成 更新 デザイナー', say: ['見た目がきれいなだけではなく、企業さんが知りたい情報を、判断しやすい順番で置くことが大切です。'], ask: ['この内容を、ご自身で文章・構成・デザイン・公開まで整えられそうです？', '止まりそうなのは、文章、構成、デザイン、実績作り、更新のどこです？'], note: 'できないと言わせるためではなく、本当に必要な支援範囲を分ける。' },
  { title: 'デザイナー・支援へつなぐ', when: 'PFと実績の必要性・自作難度を本人も認めた後', tags: 'デザイナー 紹介 支援 フィードバック 相談', say: ['正直、ここまでお話を聞いて、○○さんは【強み】があるのに、PFと実績の見せ方で止まっているのがもったいないと感じています。', 'もし希望されるなら、ライター向けPFを担当しているデザイナーさんと、記事を確認できるライターさんが入る体制をご案内できます。', 'ご紹介して終わりではなく、【正式な支援範囲】までは一緒に進めます。'], ask: ['この体制なら進めてみたいと思います？まず詳しい内容を聞いてみたいです？'], note: '関係性・空き・値引き・案件数・支援期間は、その時点の正式条件だけ話す。' },
];

const cards = groups.map((g, i) => `<details class="card" data-search="${[g.title,g.when,g.tags,...g.say,...g.ask,g.note].join(' ').replace(/"/g,'&quot;')}"><summary><span>${i + 1}</span><div><b>${g.title}</b><small>${g.when}</small></div><i>＋</i></summary><div class="body">${g.say.length ? `<section class="say"><h3>そのまま使える一言</h3>${g.say.map(x=>`<p>「${x}」</p>`).join('')}</section>` : ''}<section class="ask"><h3>次に返す質問</h3>${g.ask.map(x=>`<p>「${x}」</p>`).join('')}</section><section class="note"><h3>使う条件</h3><p>${g.note}</p></section></div></details>`).join('');

export const sugiyamaPhrasesPage = `<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>杉山さんの使える言葉集｜緒方 Sales Script</title><style>
*{box-sizing:border-box}body{margin:0;background:#f5f4ef;color:#26352e;font:16px/1.75 -apple-system,BlinkMacSystemFont,"Segoe UI","Yu Gothic UI",sans-serif}header{position:sticky;top:0;z-index:5;background:#fffdf9ed;backdrop-filter:blur(9px);padding:12px 16px;border-bottom:1px solid #d9ddd8;display:flex;gap:14px;align-items:center;overflow:auto;white-space:nowrap}a{color:#286047;text-decoration:none}nav{display:flex;gap:13px}main{max-width:920px;margin:auto;padding:26px 16px 80px}h1{font-size:clamp(28px,6vw,48px);line-height:1.2;margin:0 0 8px}.lead{color:#607067;margin:0 0 18px}.rule{background:#e9f3eb;border:1px solid #c5d9ca;border-radius:15px;padding:14px 16px;margin-bottom:18px}.tools{position:sticky;top:52px;z-index:4;background:#f5f4efed;padding:10px 0}.tools input{width:100%;padding:13px 15px;border:1px solid #ccd5cf;border-radius:12px;font:inherit}.status{color:#607067;font-size:14px;margin:5px 2px 12px}.card{background:#fff;border:1px solid #d9ddd8;border-radius:15px;margin:9px 0;overflow:hidden}.card[open]{box-shadow:0 7px 22px #1a302614}.card summary{cursor:pointer;list-style:none;display:grid;grid-template-columns:auto 1fr auto;gap:11px;align-items:center;padding:15px}.card summary::-webkit-details-marker{display:none}.card summary>span{background:#e9f3eb;color:#286047;border-radius:8px;padding:3px 8px;font-weight:800}.card summary b,.card summary small{display:block}.card summary small{color:#607067;font-weight:400;line-height:1.45;margin-top:2px}.card summary i{font-size:22px;color:#286047;font-style:normal}.card[open] summary i{transform:rotate(45deg)}.body{border-top:1px solid #e0e4e0;padding:14px;display:grid;gap:10px}.body section{border-radius:12px;padding:11px 13px}.body h3{font-size:13px;margin:0 0 5px}.body p{margin:5px 0}.say{background:#edf6ef;border:1px solid #d0e2d4}.say h3{color:#286047}.ask{background:#eef5fa;border:1px solid #d3e1ea}.ask h3{color:#315c80}.note{background:#fbf7e8;border:1px solid #eadcae}.note h3{color:#876615}.danger{margin-top:24px;background:#fff0ed;border:1px solid #eccfc8;border-radius:15px;padding:14px 16px}.danger h2{font-size:18px;margin:0 0 6px}.danger p{margin:4px 0}@media(max-width:600px){header{font-size:13px}main{padding-top:20px}.tools{top:48px}.card summary{padding:13px}}
</style></head><body><header><a href="/today">← WorkOS</a><nav><a href="/sales-script">全文台本</a><a href="/sales-script/sugiyama-a">杉山さんA＋B</a><a href="/sales-script/questions">答え問題集</a><a href="/sales-script/phrases"><strong>使える言葉集</strong></a></nav></header><main><h1>杉山さんの<br>使える言葉集</h1><p class="lead">添付文字起こしから、商談中にそのまま使える形へ整えました。場面の言葉で検索できます。</p><section class="rule"><b>使い方</b><br>カードを一つだけ開き、相手の回答に合わせて一言を選びます。必ず「次に返す質問」で相手へ会話を戻します。全文を順番に読みません。</section><div class="tools"><input id="q" type="search" placeholder="検索：継続、AI、慣れてから、単価、企業、PF、デザイナー…"></div><p class="status" id="status"></p><div id="cards">${cards}</div><section class="danger"><h2>強いけれど、そのまま使わない言葉</h2><p>「クラウドワークスは全部低単価」「稼いでいる人は使わない」「履歴書がない人に仕事が回るわけがない」「良くて日雇い」「必ず1件1万円になる」。</p><p>本人の実数を先に聞き、傾向・可能性・目標例として説明します。未確認の相場、空き、値引き、関係性も事実として使いません。</p></section></main><script>const q=document.getElementById('q'),cards=[...document.querySelectorAll('.card')],status=document.getElementById('status');function draw(){const s=q.value.trim().toLowerCase();let n=0;cards.forEach(c=>{const on=!s||c.dataset.search.toLowerCase().includes(s);c.hidden=!on;if(on)n++});status.textContent=n+'件を表示'}q.oninput=draw;draw();</script></body></html>`;
