import { Goal, MonthEndState, Outcome, RecurringRule, Task } from "./types";

// Phase 1 fixture cleanup (2026-09-05): only data the user has explicitly
// confirmed as real is kept — currently GENESIS's Outcome and RecurringRules
// below. Everything else starts empty on purpose. Do not re-add invented
// tasks, goals, or monthly outcomes here; when real data for an area is
// provided, add it — never fabricate placeholders in its place.

export const goals: Goal[] = [];

const now = new Date().toISOString();

export const tasks: Task[] = [
  {
    id: "t-riala-001",
    title: "イベント3日前リマインドを投稿可能状態にする",
    description: "対象イベントについて、開催3日前に投稿するリマインド文面を作成し、必要情報を埋め、そのまま投稿可能な状態にする。",
    why: "イベントを忘れられず、参加判断・参加準備をしやすくするため",
    area: "RIALA",
    deadline: null,
    workDate: null,
    estimateMinutes: 20,
    actualMinutes: null,
    startedAt: null,
    completedAt: null,
    importance: "中",
    urgency: "低",
    aiCapability: "BLOCKED",
    aiStatus: "Blocked",
    blockedOn: ["対象イベントの情報（日時・URL・参加方法）", "投稿先"],
    status: "未着手",
    definitionOfDone: [
      "イベント名が正しい",
      "開催日時が正しい",
      "開催場所・形式が入っている",
      "イベントURLが入っている",
      "参加方法が入っている",
      "必要なら途中入退室可などの注意事項が入っている",
      "誤字脱字チェック済み",
      "投稿先が設定されている",
      "deliveryStatus = READY_TO_SEND",
    ],
    steps: [
      "対象イベント情報を取得する",
      "日時・タイトル・URL・参加方法を確認する",
      "3日前向けの文章を作成する",
      "情報不足を検出する",
      "Self-QAする",
      "outputDestinationへ保存する",
      "READY_TO_SENDへ更新する",
    ],
    overrunReason: null,
    nextImprovement: null,
    goalId: null,
    outcomeId: "o-riala-ai-ops",
    outputType: "EVENT_REMINDER",
    outputDestination: null,
    deliveryChannel: null,
    deliveryStatus: "BLOCKED",
    automationCandidate: true,
    automationType: "SCHEDULED_POST",
    source: "manual",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-riala-002",
    title: "イベント1日前リマインドを投稿可能状態にする",
    description: "対象イベントの前日に投稿する参加直前リマインドを完成させる。3日前版の単純コピーではなく、「明日開催」であることが伝わる内容にする。",
    why: "イベントを忘れられず、参加判断・参加準備をしやすくするため",
    area: "RIALA",
    deadline: null,
    workDate: null,
    estimateMinutes: 15,
    actualMinutes: null,
    startedAt: null,
    completedAt: null,
    importance: "中",
    urgency: "低",
    aiCapability: "BLOCKED",
    aiStatus: "Blocked",
    blockedOn: ["対象イベントの情報（日時・URL・参加方法）", "投稿先"],
    status: "未着手",
    definitionOfDone: [
      "イベント名・開催日時・URL・参加方法が明確",
      "明日開催であることが伝わる内容になっている",
      "誤字チェック済み",
      "deliveryStatus = READY_TO_SEND",
    ],
    steps: [
      "対象イベント情報を取得する",
      "3日前版から差分（明日開催であること）を反映した文章を作成する",
      "情報不足を検出する",
      "Self-QAする",
      "READY_TO_SENDへ更新する",
    ],
    overrunReason: null,
    nextImprovement: null,
    goalId: null,
    outcomeId: "o-riala-ai-ops",
    outputType: "EVENT_REMINDER",
    outputDestination: null,
    deliveryChannel: null,
    deliveryStatus: "BLOCKED",
    automationCandidate: true,
    automationType: "SCHEDULED_POST",
    source: "manual",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-riala-003",
    title: "イベント当日リマインドを投稿可能状態にする",
    description: "本日開催であることが一目でわかり、直前でも参加しやすい当日リマインドを完成させる。",
    why: "イベントを忘れられず、参加判断・参加準備をしやすくするため",
    area: "RIALA",
    deadline: null,
    workDate: null,
    estimateMinutes: 15,
    actualMinutes: null,
    startedAt: null,
    completedAt: null,
    importance: "中",
    urgency: "低",
    aiCapability: "BLOCKED",
    aiStatus: "Blocked",
    blockedOn: ["対象イベントの情報（日時・URL・参加方法）", "投稿先"],
    status: "未着手",
    definitionOfDone: [
      "本日開催であることが分かる",
      "開催時刻が目立つ",
      "参加URLがある",
      "参加方法がある",
      "直前参加しやすい文章になっている",
      "deliveryStatus = READY_TO_SEND",
    ],
    steps: [
      "対象イベント情報を取得する",
      "当日向けの文章を作成する（開催時刻を目立たせる）",
      "情報不足を検出する",
      "Self-QAする",
      "READY_TO_SENDへ更新する",
    ],
    overrunReason: null,
    nextImprovement: null,
    goalId: null,
    outcomeId: "o-riala-ai-ops",
    outputType: "EVENT_REMINDER",
    outputDestination: null,
    deliveryChannel: null,
    deliveryStatus: "BLOCKED",
    automationCandidate: true,
    automationType: "SCHEDULED_POST",
    source: "manual",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-riala-004",
    title: "RIALAメンバーの移行状況を分類する",
    description: "対象メンバーについて、現在の移行状況を確認し、次の対応が分かる状態にする。",
    why: "移行できていない人を放置せず、全員に次Actionがある状態にするため",
    area: "RIALA",
    deadline: null,
    workDate: null,
    estimateMinutes: 40,
    actualMinutes: null,
    startedAt: null,
    completedAt: null,
    importance: "高",
    urgency: "中",
    aiCapability: "BLOCKED",
    aiStatus: "Blocked",
    blockedOn: ["対象メンバーの一覧・現在の移行状況データ"],
    status: "未着手",
    definitionOfDone: [
      "全対象者にMIGRATED / NOT_MIGRATED / NO_ACTION_NEEDED / UNKNOWNのいずれかが付いている",
      "UNKNOWNの人には確認Actionが設定されている",
      "NOT_MIGRATEDの人には次回フォロー方法が設定されている",
      "対象漏れがない",
    ],
    steps: [
      "対象メンバー一覧を取得する",
      "各メンバーの現在の移行状況を確認する",
      "MIGRATED / NOT_MIGRATED / NO_ACTION_NEEDED / UNKNOWNに分類する",
      "UNKNOWNに確認Actionを設定する",
      "NOT_MIGRATEDに次回フォロー方法を設定する",
    ],
    overrunReason: null,
    nextImprovement: null,
    goalId: null,
    outcomeId: "o-riala-ai-ops",
    outputType: "MEMBER_STATUS_LIST",
    outputDestination: null,
    deliveryChannel: null,
    deliveryStatus: null,
    automationCandidate: true,
    automationType: "STATUS_CLASSIFICATION",
    source: "manual",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-riala-005",
    title: "未移行者向けフォロー文面を送信可能状態にする",
    description: "未移行者に対して、以前送付済みの案内やリンクを前提に、再度移行を促す文面を作成する。",
    why: "未移行者が迷わず移行Actionを取れるようにするため",
    area: "RIALA",
    deadline: null,
    workDate: null,
    estimateMinutes: 20,
    actualMinutes: null,
    startedAt: null,
    completedAt: null,
    importance: "中",
    urgency: "中",
    aiCapability: "BLOCKED",
    aiStatus: "Blocked",
    blockedOn: ["未移行者の対象者情報", "以前送付済みの案内内容・リンク"],
    status: "未着手",
    definitionOfDone: [
      "対象者が明確",
      "以前案内済みであることを前提にしている",
      "必要なリンクが入っている",
      "強すぎない催促になっている",
      "次に何をしてほしいかが明確",
      "deliveryStatus = READY_TO_SEND",
    ],
    steps: [
      "未移行者の対象者を確認する",
      "以前の案内内容・リンクを確認する",
      "フォロー文面を作成する",
      "Self-QAで催促の強さを確認する",
      "READY_TO_SENDへ更新する",
    ],
    overrunReason: null,
    nextImprovement: null,
    goalId: null,
    outcomeId: "o-riala-ai-ops",
    outputType: "MESSAGE_DRAFT",
    outputDestination: null,
    deliveryChannel: null,
    deliveryStatus: "BLOCKED",
    automationCandidate: true,
    automationType: "AUTO_MESSAGE",
    source: "manual",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-riala-006",
    title: "移行済み者向け案内文面を送信可能状態にする",
    description: "移行完了者向けに、不要な再移行依頼を含まない案内文面を作成する。",
    why: "移行済みの人に誤った・不要な依頼を送らず、必要な案内だけ届けるため",
    area: "RIALA",
    deadline: null,
    workDate: null,
    estimateMinutes: 20,
    actualMinutes: null,
    startedAt: null,
    completedAt: null,
    importance: "低",
    urgency: "低",
    aiCapability: "BLOCKED",
    aiStatus: "Blocked",
    blockedOn: ["移行済み対象者情報", "次に案内すべき内容の有無"],
    status: "未着手",
    definitionOfDone: [
      "移行完了者向け内容になっている",
      "不要な再移行依頼がない",
      "次に案内すべきことがあれば記載されている",
      "deliveryStatus = READY_TO_SEND",
    ],
    steps: [
      "移行済み対象者を確認する",
      "次に案内すべき内容があるか確認する",
      "案内文面を作成する",
      "Self-QAで再移行依頼が混ざっていないか確認する",
      "READY_TO_SENDへ更新する",
    ],
    overrunReason: null,
    nextImprovement: null,
    goalId: null,
    outcomeId: "o-riala-ai-ops",
    outputType: "MESSAGE_DRAFT",
    outputDestination: null,
    deliveryChannel: null,
    deliveryStatus: "BLOCKED",
    automationCandidate: true,
    automationType: "AUTO_MESSAGE",
    source: "manual",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-riala-007",
    title: "RIALA定型業務のAI移管範囲を整理する",
    description: "現在行っている主要運営業務について、AIに任せる部分と、人間が判断する部分を整理する。",
    why: "AIで実際に運営を代行できる範囲を明確にするため",
    area: "RIALA",
    deadline: null,
    workDate: null,
    estimateMinutes: 45,
    actualMinutes: null,
    startedAt: null,
    completedAt: null,
    importance: "中",
    urgency: "低",
    aiCapability: "HYBRID",
    aiStatus: "未着手",
    blockedOn: null,
    status: "未着手",
    definitionOfDone: [
      "主要業務ごとに、業務名・目的・入力情報・完成成果物・aiCapability・人間確認の要否・外部権限の要否・保存先・投稿先/送信先・自動化候補かどうかが整理されている",
    ],
    steps: [
      "現在の主要運営業務を洗い出す",
      "業務ごとに目的・入力情報・完成成果物を整理する",
      "aiCapabilityを判定する",
      "人間確認・外部権限の要否を確認する",
      "保存先・投稿先を整理する",
      "自動化候補かどうかを判定する",
    ],
    overrunReason: null,
    nextImprovement: null,
    goalId: null,
    outcomeId: "o-riala-ai-ops",
    outputType: "OPERATION_DOC",
    outputDestination: null,
    deliveryChannel: null,
    deliveryStatus: null,
    automationCandidate: false,
    automationType: "NONE",
    source: "manual",
    createdAt: now,
    updatedAt: now,
  },
];

export const monthEndStates: MonthEndState[] = [];

export const outcomes: Outcome[] = [
  {
    id: "o-riala-ai-ops",
    area: "RIALA",
    title: "RIALA運営をAI中心で回せる状態にする",
    desiredState:
      "定型的なコミュニティ運営業務について、AIが必要情報を集約し、そのまま投稿・送信・確認に使える成果物まで作成できている。人間は、方針判断・承認・例外対応など、人間にしかできない部分へ集中している。",
    why: "毎回ゼロから文章や対応を考える時間を減らすため。運営漏れをなくすため。イベント案内や移行対応などの品質を一定に保つため。AIに任せられる業務と人間が判断すべき業務を分けるため。将来的な予約投稿・自動化へつなげるため。",
    achievementCriteria: [
      "イベント3日前リマインドをAIで作成可能",
      "イベント1日前リマインドをAIで作成可能",
      "当日リマインドをAIで作成可能",
      "未移行者フォロー文面をAIで作成可能",
      "移行済み者向け文面をAIで作成可能",
      "移行状況一覧を管理可能",
      "各成果物に保存先・送信先がある",
      "AI/Humanの担当区分が整理されている",
    ],
    status: "ACTIVE",
  },
  {
    id: "o-genesis-60day",
    area: "GENESIS",
    title: "60日チャレンジ",
    desiredState:
      "感情で「大丈夫」と判断するのではなく、目的から逆算して必要な行動・期限・予定時間を決め、決めた時間と期限を厳守して実行できる状態になる。さらに、出来事を具体だけで捉えず、具体→抽象→別の具体へ展開し、再現性のある考え方として使える状態になる。",
    why: "時間や期限を感覚で扱わない自分になるため。「なんとかなる」で予定を組まず、事実と逆算で管理するため。タスク量・期限・実行時間を正しく見積もれるようになるため。問題発生時に感情ではなく構造から原因を考えるため。個別の出来事から学びを抽象化し、別の場面でも使えるようにするため。",
    achievementCriteria: [
      "毎日の全量タスクを確認し、必要なタスクに期限が設定されている",
      "期限から逆算して「その日にどこまで終わっている必要があるか」が決められている",
      "実行タスクがGoogle Calendar等の予定に入っている",
      "予定時間と完了予定日を基準に実行している",
      "予定時間を超過した場合、超過原因が記録されている",
      "期限に間に合わない場合、原因と再計画が記録されている",
      "原因分析時に、手段そのものを目的化せず、「何のためにやっているか」から再整理している",
      "具体⇄抽象トレーニングを毎日30分以上実施している",
      "毎日2本、出来事→目的→理想→事実→問題→原因→Actionの形でアウトプットしている",
    ],
    status: "ACTIVE",
  },
];

export const recurringRules: RecurringRule[] = [
  {
    id: "r-001",
    title: "具体⇄抽象トレーニング 30分以上",
    frequency: "DAILY",
    area: "GENESIS",
    estimateMinutes: 30,
    aiCapability: "HYBRID",
    description: "出来事・課題・行動について、具体→抽象→別の具体へ展開し、個別事象だけで終わらない考え方を身につける。",
    definitionOfDone: [
      "合計30分以上実施している",
      "具体→抽象を最低1回行っている",
      "抽象→別の具体例への展開を最低1回行っている",
      "自分の言葉で説明できる状態になっている",
    ],
    allowedMedium: ["紙", "音声", "ChatGPT等AIとの壁打ち", "テキスト", "その他"],
    why: "個別事象だけで判断せず、構造を捉え、別の問題にも応用できる思考を身につけるため。",
    outcomeId: "o-genesis-60day",
    streakDays: 2,
  },
  {
    id: "r-002",
    title: "問題解決アウトプット2本",
    frequency: "DAILY",
    area: "GENESIS",
    estimateMinutes: null,
    aiCapability: "HYBRID",
    description:
      "その日に起きた出来事や考えたいテーマを、感情や自己解釈だけで終わらせず、出来事→目的→理想→事実→問題→原因→Actionの構造に沿って2本アウトプットする。",
    definitionOfDone: [
      "2テーマについて、出来事・目的・理想・事実・問題・原因・Actionがそれぞれ埋まっている",
    ],
    allowedMedium: ["紙", "言葉", "ChatGPT等AIとの壁打ち", "テキスト", "その他"],
    why: "推測や感情を事実化せず、目的と事実から問題を定義し、再現性のある改善Actionを作れるようにするため。",
    outcomeId: "o-genesis-60day",
    streakDays: 5,
  },
  {
    id: "r-003",
    title: "全量タスク→期限→当日必要量をCalendarへ落とし、実行する",
    frequency: "DAILY",
    area: "GENESIS",
    estimateMinutes: null,
    aiCapability: "HYBRID",
    description: "全タスクを目的から逆算し、期限・予定時間・実行日を決め、その日に終える必要量をCalendarへ配置して実行する。",
    definitionOfDone: [
      "未期限タスクが確認されている",
      "必要タスクに期限が設定されている",
      "期限から逆算して今日終える必要量が決まっている",
      "Google Calendar等に実行時間が確保されている",
      "実行済み・未達が明確になっている",
      "予定時間を超えた場合、原因が記録されている",
      "期限に間に合わない場合、原因と再計画が記録されている",
    ],
    allowedMedium: ["Google Calendar", "その他"],
    why: "「多分大丈夫」ではなく、実在する時間と期限から逆算して行動できる自分になるため。",
    outcomeId: "o-genesis-60day",
    streakDays: 0,
  },
];
