import { Goal, MonthEndState, RecurringTask, Task } from "./types";
import { monthKeyOf, offsetYmd } from "./date";

const now = new Date().toISOString();

export const goals: Goal[] = [
  {
    id: "g-purpose",
    parentId: null,
    title: "人生の目的・価値観",
    targetDate: null,
    desiredState: "お金・場所・時間に縛られず、自分で選んだ働き方で生きている",
    achievementCriteria: "収入・拠点・時間の使い方を自分の意思で決められている状態",
    status: "進行中",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "g-5y",
    parentId: "g-purpose",
    title: "5年後：複数の収入源を持つ経営者",
    targetDate: "2031-08-31",
    desiredState: "会社に依存しない月1,000万円規模の事業基盤ができている",
    achievementCriteria: "月次売上1,000万円 かつ 主要業務がAI/チームに移管済み",
    status: "進行中",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "g-3y",
    parentId: "g-5y",
    title: "3年後：会社を辞めて独立",
    targetDate: "2029-08-31",
    desiredState: "本業を辞め、事業所得だけで生活できている",
    achievementCriteria: "事業の月次利益が本業手取りを継続して上回っている",
    status: "進行中",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "g-1y",
    parentId: "g-3y",
    title: "1年後：会社外収入 月53万円",
    targetDate: "2027-08-31",
    desiredState: "B2B AI受託・自動化と営業代行で安定収入を得ている",
    achievementCriteria: "会社外月次収入が3ヶ月連続で53万円以上",
    status: "進行中",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "g-3m",
    parentId: "g-1y",
    title: "3か月後：営業代行を開始し初受注",
    targetDate: offsetYmd(75),
    desiredState: "営業代行の型ができ、最初のクライアントから成果報酬が発生している",
    achievementCriteria: "営業代行案件を1件受注し、アポ譲渡が発生している",
    status: "進行中",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "g-1m",
    parentId: "g-3m",
    title: "1か月後：営業代行の準備を完了する",
    targetDate: offsetYmd(25),
    desiredState: "営業開始に必要な理解・トーク・ターゲットリストが揃っている",
    achievementCriteria: "研修修了・トークスクリプト完成・アプローチリスト30件準備完了",
    status: "進行中",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "g-week",
    parentId: "g-1m",
    title: "今週：研修動画を見て要点を記録する",
    targetDate: offsetYmd(3),
    desiredState: "研修内容を理解し、自分の言葉で要点をまとめられている",
    achievementCriteria: "研修動画を全て視聴し、要点メモを提出できる状態",
    status: "進行中",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "g-outcome-training",
    parentId: "g-week",
    title: "必要な成果：研修①②の理解を証明する",
    targetDate: offsetYmd(3),
    desiredState: "研修内容を要点メモとして言語化できている",
    achievementCriteria: "要点メモ3項目以上・自分の言葉で説明できる",
    status: "進行中",
    createdAt: now,
    updatedAt: now,
  },
];

export const tasks: Task[] = [
  {
    id: "t-001",
    title: "研修動画①②を視聴し、重要点を記録する",
    area: "営業代行",
    deadline: offsetYmd(3),
    workDate: offsetYmd(0),
    estimateMinutes: 60,
    importance: "高",
    urgency: "高",
    owner: "Human",
    aiMode: null,
    status: "未着手",
    aiStatus: null,
    definitionOfDone: "要点メモを3項目以上まとめている",
    goalId: "g-outcome-training",
    source: "manual",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-002",
    title: "トークスクリプトの下書きを作成する",
    area: "営業代行",
    deadline: offsetYmd(6),
    workDate: offsetYmd(0),
    estimateMinutes: 20,
    importance: "中",
    urgency: "中",
    owner: "AI",
    aiMode: "Draft",
    status: "進行中",
    aiStatus: "実行中",
    definitionOfDone: "アポ獲得トークの初稿ができている",
    goalId: "g-1m",
    source: "ai",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-003",
    title: "アプローチ先候補を30件リストアップする",
    area: "営業代行",
    deadline: offsetYmd(20),
    workDate: null,
    estimateMinutes: 90,
    importance: "高",
    urgency: "低",
    owner: "Human",
    aiMode: null,
    status: "未着手",
    aiStatus: null,
    definitionOfDone: "業種・規模を満たす候補が30件リスト化されている",
    goalId: "g-1m",
    source: "manual",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-004",
    title: "契約書のフォーマットを確認する",
    area: "営業代行",
    deadline: offsetYmd(-2),
    workDate: null,
    estimateMinutes: 15,
    importance: "中",
    urgency: "高",
    owner: "Human",
    aiMode: null,
    status: "未着手",
    aiStatus: null,
    definitionOfDone: "自分が使う契約書フォーマットを確定している",
    goalId: "g-3m",
    source: "manual",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-005",
    title: "note連載の今週回を書く",
    area: "その他",
    deadline: offsetYmd(1),
    workDate: offsetYmd(0),
    estimateMinutes: 40,
    importance: "中",
    urgency: "中",
    owner: "AI",
    aiMode: "Draft",
    status: "進行中",
    aiStatus: "人間確認待ち",
    definitionOfDone: "下書きが完成し、本人確認待ちになっている",
    goalId: null,
    source: "ai",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-006",
    title: "GENESISの課題②を提出する",
    area: "GENESIS",
    deadline: offsetYmd(0),
    workDate: offsetYmd(0),
    estimateMinutes: 45,
    importance: "高",
    urgency: "高",
    owner: "Human",
    aiMode: null,
    status: "未着手",
    aiStatus: null,
    definitionOfDone: "課題を提出し、提出確認が取れている",
    goalId: null,
    source: "manual",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-007",
    title: "RIALAのDM対応テンプレを整理する",
    area: "RIALA",
    deadline: offsetYmd(4),
    workDate: null,
    estimateMinutes: 30,
    importance: "中",
    urgency: "低",
    owner: "Hybrid",
    aiMode: "Assist",
    status: "未着手",
    aiStatus: "未着手",
    definitionOfDone: "よくある質問3パターンのテンプレが揃っている",
    goalId: null,
    source: "manual",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-008",
    title: "RIALA運営マニュアルの入会フローを更新する",
    area: "RIALA",
    deadline: offsetYmd(9),
    workDate: null,
    estimateMinutes: 25,
    importance: "低",
    urgency: "低",
    owner: "AI",
    aiMode: "Execute",
    status: "完了",
    aiStatus: "完了",
    definitionOfDone: "マニュアルの該当ページが最新化されている",
    goalId: null,
    source: "ai",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-009",
    title: "見積書テンプレの修正版を反映する",
    area: "その他",
    deadline: offsetYmd(-5),
    workDate: null,
    estimateMinutes: 20,
    importance: "中",
    urgency: "中",
    owner: "Human",
    aiMode: null,
    status: "完了",
    aiStatus: null,
    definitionOfDone: "最新の単価表が反映されている",
    goalId: null,
    source: "manual",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-010",
    title: "在庫の値下げ対象を洗い出す",
    area: "その他",
    deadline: offsetYmd(2),
    workDate: null,
    estimateMinutes: 30,
    importance: "中",
    urgency: "中",
    owner: "AI",
    aiMode: "Decision",
    status: "待ち",
    aiStatus: "人間確認待ち",
    definitionOfDone: "値下げ候補と根拠がリスト化されている",
    goalId: null,
    source: "ai",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-011",
    title: "週次KPIレビューを確認する",
    area: "その他",
    deadline: offsetYmd(5),
    workDate: null,
    estimateMinutes: 15,
    importance: "低",
    urgency: "低",
    owner: "Human",
    aiMode: null,
    status: "待ち",
    aiStatus: null,
    definitionOfDone: "先週比の増減を把握している",
    goalId: null,
    source: "manual",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-012",
    title: "自己紹介文をブラッシュアップする",
    area: "営業代行",
    deadline: offsetYmd(8),
    workDate: null,
    estimateMinutes: 30,
    importance: "中",
    urgency: "中",
    owner: "Hybrid",
    aiMode: "Draft",
    status: "進行中",
    aiStatus: "実行中",
    definitionOfDone: "接客業の実績を軸にした短い自己紹介ができている",
    goalId: "g-3m",
    source: "manual",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-013",
    title: "GENESIS課題③に着手する",
    area: "GENESIS",
    deadline: offsetYmd(12),
    workDate: null,
    estimateMinutes: 60,
    importance: "中",
    urgency: "低",
    owner: "Human",
    aiMode: null,
    status: "未着手",
    aiStatus: null,
    definitionOfDone: "課題の下調べと骨子ができている",
    goalId: null,
    source: "manual",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-014",
    title: "TikTok投稿の台本を3本作る",
    area: "その他",
    deadline: offsetYmd(7),
    workDate: null,
    estimateMinutes: 50,
    importance: "中",
    urgency: "中",
    owner: "AI",
    aiMode: "Draft",
    status: "未着手",
    aiStatus: "未着手",
    definitionOfDone: "写真と内容が一致した台本が3本ある",
    goalId: null,
    source: "ai",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-015",
    title: "Notionポートフォリオのリンク切れを確認する",
    area: "営業代行",
    deadline: offsetYmd(-1),
    workDate: null,
    estimateMinutes: 10,
    importance: "低",
    urgency: "中",
    owner: "Human",
    aiMode: null,
    status: "未着手",
    aiStatus: null,
    definitionOfDone: "全リンクが正常に開けることを確認済み",
    goalId: "g-3m",
    source: "manual",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-016",
    title: "月次振り返りをAddnessに記録する",
    area: "その他",
    deadline: offsetYmd(15),
    workDate: null,
    estimateMinutes: 20,
    importance: "中",
    urgency: "低",
    owner: "Human",
    aiMode: null,
    status: "未着手",
    aiStatus: null,
    definitionOfDone: "先月比の達成状況がAddnessに記録されている",
    goalId: "g-1y",
    source: "manual",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-017",
    title: "RIALAの新規入会者フォロー文面を送る",
    area: "RIALA",
    deadline: offsetYmd(1),
    workDate: offsetYmd(0),
    estimateMinutes: 15,
    importance: "高",
    urgency: "高",
    owner: "AI",
    aiMode: "Draft",
    status: "進行中",
    aiStatus: "人間確認待ち",
    definitionOfDone: "下書きが完成し送信待ちになっている",
    goalId: null,
    source: "ai",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-018",
    title: "カーセンサー掲載費の解約要否を判断する",
    area: "その他",
    deadline: offsetYmd(10),
    workDate: null,
    estimateMinutes: 20,
    importance: "中",
    urgency: "低",
    owner: "Hybrid",
    aiMode: "Decision",
    status: "未着手",
    aiStatus: "未着手",
    definitionOfDone: "継続/解約の判断と根拠が明確になっている",
    goalId: null,
    source: "manual",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-019",
    title: "AI Work OSのPhase1を触ってみる",
    area: "その他",
    deadline: offsetYmd(0),
    workDate: offsetYmd(0),
    estimateMinutes: 15,
    importance: "高",
    urgency: "中",
    owner: "Human",
    aiMode: null,
    status: "未着手",
    aiStatus: null,
    definitionOfDone: "毎日見たいと思えるか判断できている",
    goalId: null,
    source: "manual",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-020",
    title: "先月分の請求書を発行する",
    area: "その他",
    deadline: offsetYmd(-10),
    workDate: null,
    estimateMinutes: 15,
    importance: "中",
    urgency: "中",
    owner: "Human",
    aiMode: null,
    status: "完了",
    aiStatus: null,
    definitionOfDone: "請求書を送付済み",
    goalId: null,
    source: "manual",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-021",
    title: "GENESIS課題①のフィードバックを反映する",
    area: "GENESIS",
    deadline: offsetYmd(-3),
    workDate: null,
    estimateMinutes: 30,
    importance: "中",
    urgency: "中",
    owner: "Human",
    aiMode: null,
    status: "完了",
    aiStatus: null,
    definitionOfDone: "指摘点を反映し再提出済み",
    goalId: null,
    source: "manual",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-022",
    title: "来月のカレンダー作業予定を仮組みする",
    area: "その他",
    deadline: offsetYmd(18),
    workDate: null,
    estimateMinutes: 20,
    importance: "低",
    urgency: "低",
    owner: "Human",
    aiMode: null,
    status: "未着手",
    aiStatus: null,
    definitionOfDone: "翌月の作業予定が前日確定ルールに沿って仮組みされている",
    goalId: null,
    source: "manual",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-023",
    title: "営業代行案件の想定Q&Aを準備する",
    area: "営業代行",
    deadline: offsetYmd(35),
    workDate: null,
    estimateMinutes: 40,
    importance: "中",
    urgency: "低",
    owner: "AI",
    aiMode: "Draft",
    status: "未着手",
    aiStatus: "未着手",
    definitionOfDone: "想定質問と回答例が10個以上ある",
    goalId: "g-3m",
    source: "ai",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-024",
    title: "来月のRIALA運営タスクを棚卸しする",
    area: "RIALA",
    deadline: offsetYmd(32),
    workDate: null,
    estimateMinutes: 30,
    importance: "中",
    urgency: "低",
    owner: "Human",
    aiMode: null,
    status: "未着手",
    aiStatus: null,
    definitionOfDone: "来月分の定型タスクがリスト化されている",
    goalId: null,
    source: "manual",
    createdAt: now,
    updatedAt: now,
  },
];

export const monthEndStates: MonthEndState[] = [
  {
    monthKey: monthKeyOf(0),
    area: "営業代行",
    state: "営業開始に必要な理解と準備が完了している",
  },
  {
    monthKey: monthKeyOf(0),
    area: "RIALA",
    state: "定型運営業務のAI移管範囲が整理されている",
  },
  {
    monthKey: monthKeyOf(0),
    area: "GENESIS",
    state: "期限付き課題を継続している",
  },
  {
    monthKey: monthKeyOf(1),
    area: "営業代行",
    state: "アプローチリストが完成し、初回アプローチを開始している",
  },
  {
    monthKey: monthKeyOf(1),
    area: "RIALA",
    state: "DM対応テンプレが揃い、対応時間が短縮されている",
  },
  {
    monthKey: monthKeyOf(1),
    area: "GENESIS",
    state: "課題の提出率90%を維持できている",
  },
];

export const recurringTasks: RecurringTask[] = [
  { id: "r-001", title: "アウトプット2本" },
  { id: "r-002", title: "抽象⇄具体をAIと10分壁打ち" },
  { id: "r-003", title: "日報" },
];
