import {
  AiOperationMatrixEntry,
  Goal,
  LiveSalesFeedback,
  MonthEndState,
  OperationalAudit,
  OperationCategory,
  Outcome,
  PractitionerFeedback,
  RecurringRule,
  RoleplayFeedback,
  SalesPhase,
  SalesSprint,
  Task,
  Workflow,
} from "./types";

// Phase 1 fixture cleanup (2026-09-05): only data the user has explicitly
// confirmed as real is kept — currently GENESIS's Outcome and RecurringRules
// below. Everything else starts empty on purpose. Do not re-add invented
// tasks, goals, or monthly outcomes here; when real data for an area is
// provided, add it — never fabricate placeholders in its place.

export const goals: Goal[] = [];

const now = new Date().toISOString();

export const tasks: Task[] = [
  {
    id: "t-riala-007",
    title: "RIALA定型業務のAI移管範囲を確定する",
    description: "RIALA Operations Masterに存在する主要業務について、AI Operation Matrix（Trigger/入力/AI Capability/AIの作業/人間の作業/Output/保存先/完了条件/Block条件）を完成させる。",
    why: "AIで実際に運営を代行できる範囲を明確にし、候補（candidate）のままの分類を確定させるため",
    area: "RIALA",
    deadline: null,
    workDate: null,
    estimateMinutes: 45,
    actualMinutes: null,
    startedAt: null,
    completedAt: null,
    importance: "中",
    urgency: "低",
    aiCapability: "HYBRID",
    aiStatus: "未着手",
    blockedOn: null,
    status: "未着手",
    definitionOfDone: [
      "Operations Master上の主要業務それぞれにTrigger・Required Input・AI Capability・AIがやること・Humanがやること・Output・Output Destination・Completion Condition・Block条件が定義されている",
      "現在candidate扱いのAI Capability分類が確定済みに更新されている",
    ],
    steps: [
      "Operations Masterの7カテゴリを確認する",
      "各カテゴリのWorkflowを確認する",
      "AI Operation Matrixのcandidate分類を実態と照らして確定させる",
      "確定できないものはUNKNOWN/BLOCKEDのまま保持する",
    ],
    overrunReason: null,
    nextImprovement: null,
    goalId: null,
    outcomeId: "o-riala-ai-ops",
    outputType: "OPERATION_DOC",
    outputDestination: null,
    deliveryChannel: null,
    deliveryStatus: null,
    automationCandidate: false,
    automationType: "NONE",
    linkedSalesMaster: false,
    parentOperationId: "oc-07",
    workflowId: null,
    requiredInputs: [],
    notes: "完了したらDoDをOperation Matrix完成へ更新済みとしてstatusをDONEにする。いつまでも未完了で残さない。",
    source: "manual",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-sales-001",
    title: "営業17フェーズの全体像を理解する",
    description: "営業17フェーズを通しで読み、商談がなぜこの順番で進むのかを理解する。",
    why: "17個を丸暗記するのではなく、営業の全体構造を頭に入れるため",
    area: "営業代行",
    deadline: "2026-09-07",
    workDate: null,
    estimateMinutes: 60,
    actualMinutes: null,
    startedAt: null,
    completedAt: null,
    importance: "高",
    urgency: "高",
    aiCapability: "HYBRID",
    aiStatus: "未着手",
    blockedOn: null,
    status: "未着手",
    definitionOfDone: [
      "17フェーズを一度最後まで読んだ",
      "商談がなぜこの順番で進むのか説明できる",
      "前半・中盤・後半がそれぞれ何をしているか説明できる",
      "「次へ進む条件」が重要な理由を説明できる",
      "営業＝商品説明ではない理由を説明できる",
      "分からないフェーズを特定できている",
    ],
    steps: [
      "17フェーズを通しで読む",
      "前半・中盤・後半のまとまりを意識する",
      "「次へ進む条件」がある理由を考える",
      "分からない・自信がないフェーズをメモする",
    ],
    overrunReason: null,
    nextImprovement: null,
    goalId: null,
    outcomeId: null,
    outputType: null,
    outputDestination: null,
    deliveryChannel: null,
    deliveryStatus: null,
    automationCandidate: false,
    automationType: "NONE",
    linkedSalesMaster: true,
    parentOperationId: null,
    workflowId: null,
    requiredInputs: [],
    notes: null,
    source: "manual",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-sales-002",
    title: "営業商談設計書v1 前半を作る",
    description: "17フェーズのうち前半（01〜09）について、自分の理解・自分の質問・自分のトーク・次フェーズへのつなぎを営業Masterへ書き込む。",
    why: "PDFの転記で終わらせず、自分の言葉で使える状態にするため",
    area: "営業代行",
    deadline: "2026-09-07",
    workDate: null,
    estimateMinutes: 90,
    actualMinutes: null,
    startedAt: null,
    completedAt: null,
    importance: "高",
    urgency: "高",
    aiCapability: "HYBRID",
    aiStatus: "未着手",
    blockedOn: null,
    status: "未着手",
    definitionOfDone: [
      "前半フェーズ（01〜09）それぞれにPurposeを自分の言葉で書いた",
      "OK状態を自分の言葉で書いた",
      "確認事項が分かる状態にした",
      "自分が使う質問を最低1つ書いた",
      "自分のトーク・言い回しを最低1つ書いた",
      "次フェーズへのつなぎ方を考えた",
    ],
    steps: [
      "対象フェーズ（01〜09）を順に開く",
      "自分の理解を書く",
      "自分が使う質問を考える",
      "自分のトークを考える",
      "次フェーズへのつなぎを考える",
    ],
    overrunReason: null,
    nextImprovement: null,
    goalId: null,
    outcomeId: null,
    outputType: null,
    outputDestination: null,
    deliveryChannel: null,
    deliveryStatus: null,
    automationCandidate: false,
    automationType: "NONE",
    linkedSalesMaster: true,
    parentOperationId: null,
    workflowId: null,
    requiredInputs: [],
    notes: null,
    source: "manual",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-sales-003",
    title: "営業商談設計書v1 後半を作る",
    description: "17フェーズのうち後半（10〜17）について、自分の理解・自分の質問・自分のトーク・次フェーズへのつなぎを営業Masterへ書き込む。",
    why: "PDFの転記で終わらせず、自分の言葉で使える状態にするため",
    area: "営業代行",
    deadline: "2026-09-08",
    workDate: null,
    estimateMinutes: 90,
    actualMinutes: null,
    startedAt: null,
    completedAt: null,
    importance: "高",
    urgency: "高",
    aiCapability: "HYBRID",
    aiStatus: "未着手",
    blockedOn: null,
    status: "未着手",
    definitionOfDone: [
      "後半フェーズ（10〜17）それぞれにPurposeを自分の言葉で書いた",
      "OK状態を自分の言葉で書いた",
      "確認事項が分かる状態にした",
      "自分が使う質問を最低1つ書いた",
      "自分のトーク・言い回しを最低1つ書いた",
      "次フェーズへのつなぎ方を考えた",
      "17フェーズが一周完成した",
    ],
    steps: [
      "対象フェーズ（10〜17）を順に開く",
      "自分の理解を書く",
      "自分が使う質問を考える",
      "自分のトークを考える",
      "次フェーズへのつなぎを考える",
    ],
    overrunReason: null,
    nextImprovement: null,
    goalId: null,
    outcomeId: null,
    outputType: null,
    outputDestination: null,
    deliveryChannel: null,
    deliveryStatus: null,
    automationCandidate: false,
    automationType: "NONE",
    linkedSalesMaster: true,
    parentOperationId: null,
    workflowId: null,
    requiredInputs: [],
    notes: null,
    source: "manual",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-sales-004",
    title: "実践者FBを営業Masterへ統合する",
    description: "実践者からの6件のFBを、関連する各SalesPhaseへ紐づけて統合する。",
    why: "FBを単発メモのまま放置せず、該当フェーズで参照できる状態にするため",
    area: "営業代行",
    deadline: "2026-09-08",
    workDate: null,
    estimateMinutes: 30,
    actualMinutes: null,
    startedAt: null,
    completedAt: null,
    importance: "中",
    urgency: "中",
    aiCapability: "AI_DRAFT",
    aiStatus: "未着手",
    blockedOn: null,
    status: "未着手",
    definitionOfDone: [
      "6件の実践者FBがそれぞれ関連フェーズに紐づいている",
      "各フェーズ詳細画面でFBが確認できる",
    ],
    steps: ["FBの内容を確認する", "関連フェーズを判定する", "各フェーズへ紐づける"],
    overrunReason: null,
    nextImprovement: null,
    goalId: null,
    outcomeId: null,
    outputType: null,
    outputDestination: null,
    deliveryChannel: null,
    deliveryStatus: null,
    automationCandidate: false,
    automationType: "NONE",
    linkedSalesMaster: true,
    parentOperationId: null,
    workflowId: null,
    requiredInputs: [],
    notes: null,
    source: "ai",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-sales-005",
    title: "重要フェーズを口頭練習する",
    description: "自分版を書いたフェーズのうち重要度が高いものを、実際に声に出して練習する。",
    why: "書けることと話せることは別だから",
    area: "営業代行",
    deadline: "2026-09-08",
    workDate: null,
    estimateMinutes: 45,
    actualMinutes: null,
    startedAt: null,
    completedAt: null,
    importance: "高",
    urgency: "高",
    aiCapability: "HUMAN",
    aiStatus: null,
    blockedOn: null,
    status: "未着手",
    definitionOfDone: ["重要フェーズを声に出して説明した", "詰まった箇所をメモした"],
    steps: ["重要フェーズを選ぶ", "声に出して説明する", "詰まった箇所をメモする"],
    overrunReason: null,
    nextImprovement: null,
    goalId: null,
    outcomeId: null,
    outputType: null,
    outputDestination: null,
    deliveryChannel: null,
    deliveryStatus: null,
    automationCandidate: false,
    automationType: "NONE",
    linkedSalesMaster: true,
    parentOperationId: null,
    workflowId: null,
    requiredInputs: [],
    notes: null,
    source: "manual",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-sales-006",
    title: "通しロープレを1本実施する",
    description: "17フェーズを通しでセルフロープレまたはロープレとして1本実施する。",
    why: "個別フェーズの練習と、通しでの実施は別物だから",
    area: "営業代行",
    deadline: "2026-09-09",
    workDate: null,
    estimateMinutes: 60,
    actualMinutes: null,
    startedAt: null,
    completedAt: null,
    importance: "高",
    urgency: "高",
    aiCapability: "HUMAN",
    aiStatus: null,
    blockedOn: null,
    status: "未着手",
    definitionOfDone: ["通しロープレを1本実施した", "可能なら録音した"],
    steps: ["ロープレの相手・方法を決める", "通しで実施する", "可能なら録音する"],
    overrunReason: null,
    nextImprovement: null,
    goalId: null,
    outcomeId: null,
    outputType: null,
    outputDestination: null,
    deliveryChannel: null,
    deliveryStatus: null,
    automationCandidate: false,
    automationType: "NONE",
    linkedSalesMaster: true,
    parentOperationId: null,
    workflowId: null,
    requiredInputs: [],
    notes: null,
    source: "manual",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-sales-007",
    title: "ロープレ自己FB v1を作る",
    description: "実施したロープレについて、実施日時・方法・良かった点・詰まった場所・次回改善などを整理し、自己FBとして完成させる。",
    why: "フィードバック会で的確に相談するため",
    area: "営業代行",
    deadline: "2026-09-09",
    workDate: null,
    estimateMinutes: 40,
    actualMinutes: null,
    startedAt: null,
    completedAt: null,
    importance: "中",
    urgency: "高",
    aiCapability: "HYBRID",
    aiStatus: "未着手",
    blockedOn: null,
    status: "未着手",
    definitionOfDone: [
      "実施日時・実施方法を記録した",
      "良かった点を書いた",
      "詰まった場所・説明が長くなった場所を書いた",
      "質問が出なかった場所・相手に合わせられなかった場所を書いた",
      "自分で判断できなかった場所を書いた",
      "次回改善を書いた",
      "フィードバック会で聞きたいことを書いた",
    ],
    steps: [
      "ロープレの記録・録音を振り返る",
      "良かった点・詰まった点を洗い出す",
      "次回改善を考える",
      "FB会で聞きたいことを整理する",
    ],
    overrunReason: null,
    nextImprovement: null,
    goalId: null,
    outcomeId: null,
    outputType: null,
    outputDestination: null,
    deliveryChannel: null,
    deliveryStatus: null,
    automationCandidate: false,
    automationType: "NONE",
    linkedSalesMaster: true,
    parentOperationId: null,
    workflowId: null,
    requiredInputs: [],
    notes: null,
    source: "manual",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "t-sales-008",
    title: "水曜FB会で聞く質問を整理する",
    description: "自己FBの内容をもとに、水曜のフィードバック会で聞きたい質問を整理する。",
    why: "限られたFB会の時間を有効に使うため",
    area: "営業代行",
    deadline: "2026-09-09",
    workDate: null,
    estimateMinutes: 15,
    actualMinutes: null,
    startedAt: null,
    completedAt: null,
    importance: "低",
    urgency: "中",
    aiCapability: "HYBRID",
    aiStatus: "未着手",
    blockedOn: null,
    status: "未着手",
    definitionOfDone: ["聞きたい質問が明確になっている", "優先順位がついている"],
    steps: ["自己FBを見返す", "疑問点を洗い出す", "優先順位をつける"],
    overrunReason: null,
    nextImprovement: null,
    goalId: null,
    outcomeId: null,
    outputType: null,
    outputDestination: null,
    deliveryChannel: null,
    deliveryStatus: null,
    automationCandidate: false,
    automationType: "NONE",
    linkedSalesMaster: true,
    parentOperationId: null,
    workflowId: null,
    requiredInputs: [],
    notes: null,
    source: "manual",
    createdAt: now,
    updatedAt: now,
  },
];

export const monthEndStates: MonthEndState[] = [];

export const outcomes: Outcome[] = [
  {
    id: "o-riala-ai-ops",
    area: "RIALA",
    title: "RIALA運営をAI中心で回せる状態にする",
    desiredState:
      "定型的なコミュニティ運営業務について、AIが必要情報を集約し、そのまま投稿・送信・確認に使える成果物まで作成できている。人間は、方針判断・承認・例外対応など、人間にしかできない部分へ集中している。",
    why: "RIALAの定型運営業務を毎回人間がゼロから考える状態を減らし、AIが情報整理→成果物作成→Self-QA→納品可能状態まで持っていき、人間は必要な判断・承認・対人対応へ集中できるようにするため。",
    achievementCriteria: [
      "主要運営業務がOperations Masterへ整理済み",
      "主要定型業務にWorkflowあり",
      "Master / Workflow / Actual Taskが分離されている",
      "現在実務がACTIVE / DONE / UNKNOWN等へ棚卸し済み",
      "ACTIVEな実務だけがTASK MAPに存在する",
      "主要業務のAI Capabilityが設定済み",
      "AI対象業務のOutput Destinationまで定義済み",
      "Human判断が必要な箇所が明確になっている",
      "新しいイベント・問い合わせ等が発生した時、既存WorkflowからActual Task化できる",
      "期限未設定Templateが TASK MAPに並んでいない",
    ],
    status: "ACTIVE",
  },
  {
    id: "o-genesis-60day",
    area: "GENESIS",
    title: "60日チャレンジ",
    desiredState:
      "感情で「大丈夫」と判断するのではなく、目的から逆算して必要な行動・期限・予定時間を決め、決めた時間と期限を厳守して実行できる状態になる。さらに、出来事を具体だけで捉えず、具体→抽象→別の具体へ展開し、再現性のある考え方として使える状態になる。",
    why: "時間や期限を感覚で扱わない自分になるため。「なんとかなる」で予定を組まず、事実と逆算で管理するため。タスク量・期限・実行時間を正しく見積もれるようになるため。問題発生時に感情ではなく構造から原因を考えるため。個別の出来事から学びを抽象化し、別の場面でも使えるようにするため。",
    achievementCriteria: [
      "毎日の全量タスクを確認し、必要なタスクに期限が設定されている",
      "期限から逆算して「その日にどこまで終わっている必要があるか」が決められている",
      "実行タスクがGoogle Calendar等の予定に入っている",
      "予定時間と完了予定日を基準に実行している",
      "予定時間を超過した場合、超過原因が記録されている",
      "期限に間に合わない場合、原因と再計画が記録されている",
      "原因分析時に、手段そのものを目的化せず、「何のためにやっているか」から再整理している",
      "具体⇄抽象トレーニングを毎日30分以上実施している",
      "毎日2本、出来事→目的→理想→事実→問題→原因→Actionの形でアウトプットしている",
    ],
    status: "ACTIVE",
  },
];

export const recurringRules: RecurringRule[] = [
  {
    id: "r-001",
    title: "具体⇄抽象トレーニング 30分以上",
    frequency: "DAILY",
    area: "GENESIS",
    estimateMinutes: 30,
    aiCapability: "HYBRID",
    description: "出来事・課題・行動について、具体→抽象→別の具体へ展開し、個別事象だけで終わらない考え方を身につける。",
    definitionOfDone: [
      "合計30分以上実施している",
      "具体→抽象を最低1回行っている",
      "抽象→別の具体例への展開を最低1回行っている",
      "自分の言葉で説明できる状態になっている",
    ],
    allowedMedium: ["紙", "音声", "ChatGPT等AIとの壁打ち", "テキスト", "その他"],
    why: "個別事象だけで判断せず、構造を捉え、別の問題にも応用できる思考を身につけるため。",
    outcomeId: "o-genesis-60day",
    streakDays: 2,
  },
  {
    id: "r-002",
    title: "問題解決アウトプット2本",
    frequency: "DAILY",
    area: "GENESIS",
    estimateMinutes: null,
    aiCapability: "HYBRID",
    description:
      "その日に起きた出来事や考えたいテーマを、感情や自己解釈だけで終わらせず、出来事→目的→理想→事実→問題→原因→Actionの構造に沿って2本アウトプットする。",
    definitionOfDone: [
      "2テーマについて、出来事・目的・理想・事実・問題・原因・Actionがそれぞれ埋まっている",
    ],
    allowedMedium: ["紙", "言葉", "ChatGPT等AIとの壁打ち", "テキスト", "その他"],
    why: "推測や感情を事実化せず、目的と事実から問題を定義し、再現性のある改善Actionを作れるようにするため。",
    outcomeId: "o-genesis-60day",
    streakDays: 5,
  },
  {
    id: "r-003",
    title: "全量タスク→期限→当日必要量をCalendarへ落とし、実行する",
    frequency: "DAILY",
    area: "GENESIS",
    estimateMinutes: null,
    aiCapability: "HYBRID",
    description: "全タスクを目的から逆算し、期限・予定時間・実行日を決め、その日に終える必要量をCalendarへ配置して実行する。",
    definitionOfDone: [
      "未期限タスクが確認されている",
      "必要タスクに期限が設定されている",
      "期限から逆算して今日終える必要量が決まっている",
      "Google Calendar等に実行時間が確保されている",
      "実行済み・未達が明確になっている",
      "予定時間を超えた場合、原因が記録されている",
      "期限に間に合わない場合、原因と再計画が記録されている",
    ],
    allowedMedium: ["Google Calendar", "その他"],
    why: "「多分大丈夫」ではなく、実在する時間と期限から逆算して行動できる自分になるため。",
    outcomeId: "o-genesis-60day",
    streakDays: 0,
  },
];

// --- 営業Master（Sales Playbook） ---
// The 17 phase names/order below are the user's own worksheet — fixed, never
// reordered or renamed. purpose/okState/checkPoints/sourceQuestions/
// ngExamples are that worksheet's actual content (①基礎) and are left empty
// until the real worksheet text is provided; do not invent sales-training
// content to fill them in.
const SALES_PHASE_TITLES: string[] = [
  "第一印象形成",
  "ラポール形成",
  "現状把握",
  "理想の明確化",
  "ギャップ認識",
  "原因の特定",
  "課題提示",
  "感情喚起",
  "解決可能性の提示",
  "解決策提示",
  "理解確認",
  "不安解除",
  "意志確認",
  "テスクロ",
  "オファー",
  "クロージング",
  "決済",
];

export const salesPhases: SalesPhase[] = SALES_PHASE_TITLES.map((title, i) => ({
  id: `sp-${String(i + 1).padStart(2, "0")}`,
  phaseNumber: i + 1,
  title,
  purpose: null,
  okState: null,
  checkPoints: [],
  sourceQuestions: [],
  ngExamples: [],
  myUnderstanding: null,
  myTalkExamples: [],
  myQuestions: [],
  myTransitionTalk: [],
  caseSpecificKnowledge: [],
  nextImprovement: [],
  improvementHistory: [],
  masteryStatus: "NOT_STARTED",
}));

function phaseIds(...numbers: number[]): string[] {
  return numbers.map((n) => `sp-${String(n).padStart(2, "0")}`);
}

export const practitionerFeedback: PractitionerFeedback[] = [
  {
    id: "pf-01",
    title: "「商談の型にお客様を合わせる」のではなく、「お客様に合わせながら主導権を握る」",
    content:
      "固定された順番を守ることより、相手が前のめりになれる進め方を選ぶ。質問にしっかり答える→ヒアリングを深める。まず資料を見たい→先に資料を見る。",
    source: "実践者FB",
    relatedPhaseIds: [],
    lesson: "固定された順番を守ることより、相手が前のめりになれる進め方を選ぶ。",
    exampleTalk: [],
    addedAt: now,
  },
  {
    id: "pf-02",
    title: "最初に料金を聞かれた場合",
    content:
      "料金を伝える／伝えないだけで判断せず、その後の展開まで設計する。「もちろんお伝えします。ただ、金額だけだと判断しづらいと思うので、最後まで内容を聞いていただいた上で判断してもらってもいいですか？」",
    source: "実践者FB",
    relatedPhaseIds: phaseIds(1, 11, 15),
    lesson: "料金提示と引き換えに「最後まで聞く」というYESを取る。",
    exampleTalk: [
      "もちろんお伝えします。ただ、金額だけだと判断しづらいと思うので、最後まで内容を聞いていただいた上で判断してもらってもいいですか？",
    ],
    addedAt: now,
  },
  {
    id: "pf-03",
    title: "「大丈夫です」「考えます」をそのまま受け取らない",
    content:
      "言葉だけでなく、間・声のトーン・返答速度も見る。違和感があれば具体的な不安確認へ切り替える。「ちなみに○○の部分で不安はないですか？」表面的な不安が出た場合：「もしそこが解消されたら、やってみたいと思いますか？」YES→その不安を解消。NO→別の本質的懸念を探す。",
    source: "実践者FB",
    relatedPhaseIds: phaseIds(12, 13),
    lesson: "言葉だけでなく、間・声のトーン・返答速度も見て、違和感があれば具体的な不安確認へ切り替える。",
    exampleTalk: ["ちなみに○○の部分で不安はないですか？", "もしそこが解消されたら、やってみたいと思いますか？"],
    addedAt: now,
  },
  {
    id: "pf-04",
    title: "クロージング前のYESを深くする",
    content:
      "「どうでしたか？」→「良かったです」だけで終わらせない。「率直に聞いてみて、やってみたいと思いました？」まで確認する。「良いと思う」と「自分がやりたい」を区別する。",
    source: "実践者FB",
    relatedPhaseIds: phaseIds(13, 14, 16),
    lesson: "「良いと思う」と「自分がやりたい」を区別し、後者まで確認する。",
    exampleTalk: ["率直に聞いてみて、やってみたいと思いました？"],
    addedAt: now,
  },
  {
    id: "pf-05",
    title: "カジュアルなプロフェッショナル",
    content:
      "ただ話しやすいだけでなく、「この人なら何か答えを持っていそう」と思ってもらえる状態を目指す。要素：相手の期待を超える提案／相手が知らなかった情報／卒業生・利用者事例／共感／賞賛／ねぎらい。事例はただ紹介せず、相手が「自分もこうなれそう」とイメージできるように伝える。",
    source: "実践者FB",
    relatedPhaseIds: phaseIds(1, 2, 9, 10),
    lesson: "事例は紹介するだけでなく、相手が「自分もこうなれそう」とイメージできるように伝える。",
    exampleTalk: [],
    addedAt: now,
  },
  {
    id: "pf-06",
    title: "「家族に相談します」で終わらせない",
    content:
      "相談そのものを次Actionとして設計する。整理する内容：サービス概要／本人が魅力を感じた部分／なぜ今学びたいか／始めたい理由／家族にとってのメリット・未来／安心材料。さらに「今日何時頃に相談できそうですか？」まで確認する。「相談します」ではなく「実際に相談できる状態」まで作る。",
    source: "実践者FB",
    relatedPhaseIds: phaseIds(12, 13, 16),
    lesson: "「相談します」ではなく「実際に相談できる状態」まで作る。",
    exampleTalk: ["今日何時頃に相談できそうですか？"],
    addedAt: now,
  },
];

export const roleplayFeedback: RoleplayFeedback[] = [];

export const liveSalesFeedback: LiveSalesFeedback[] = [];

export const salesSprint: SalesSprint = {
  id: "sprint-001",
  goal: "自分版・営業商談設計書v1を作り、最低1回実践し、自分の課題と質問を持ってフィードバック会へ参加する",
  checkpointLabel: "水曜10:30 営業実践クラス / FB会",
  checkpointDate: "2026-09-09",
  deliverables: [
    {
      title: "自分版・営業商談設計書 v1",
      definitionOfDone: [
        "17フェーズを一度すべて確認した",
        "自分版v1が作成されている",
        "重要フェーズは口頭練習済み",
        "最低1回通しで声に出している",
        "可能なら録音している",
      ],
    },
    {
      title: "ロープレ自己FB v1",
      definitionOfDone: ["自己FBが作成されている", "フィードバック会で聞きたいことが明確"],
    },
  ],
};

// --- RIALA Operations Master ---
// LEVEL 1 (below): what operations exist. Only categories the user has named
// — never add one on inference. LEVEL 2 (workflows): how each is processed
// when it occurs — templates, not scheduled work. LEVEL 3 (Actual Task, in
// `tasks` above): what to do, by when — only ever created for something with
// a concrete subject and a confirmed need, never for a Workflow on its own.
export const operationCategories: OperationCategory[] = [
  {
    id: "oc-01",
    categoryNumber: 1,
    area: "RIALA",
    title: "イベント運営",
    purpose: "イベント情報を受け取ったら、必要な告知・リマインドを漏れなく投稿可能状態へ持っていく。",
  },
  {
    id: "oc-02",
    categoryNumber: 2,
    area: "RIALA",
    title: "メンバー移行対応",
    purpose: "旧FANTS等から独自アプリへの移行状況を把握し、必要な人へ次のActionを届ける。",
  },
  {
    id: "oc-03",
    categoryNumber: 3,
    area: "RIALA",
    title: "問い合わせ / DM対応",
    purpose: "問い合わせに対し、既知情報で回答可能かを判定し、そのまま送信できる回答文まで作る。",
  },
  {
    id: "oc-04",
    categoryNumber: 4,
    area: "RIALA",
    title: "運営確認 / 内部連携",
    purpose: "運営判断が必要な事項を、誰に・何を・なぜ確認するか具体化した状態にする。",
  },
  {
    id: "oc-05",
    categoryNumber: 5,
    area: "RIALA",
    title: "月次状況整理 / 報告",
    purpose: "DM結果・移行状況等を、期限・提出先・フォーマットが揃った状態で整理する。",
  },
  {
    id: "oc-06",
    categoryNumber: 6,
    area: "RIALA",
    title: "定型投稿 / お知らせ",
    purpose: "イベント告知・参加方法・移行案内などの定型投稿を、テーマ・投稿先・対象が確定した時に作る。",
  },
  {
    id: "oc-07",
    categoryNumber: 7,
    area: "RIALA",
    title: "運営改善 / AI移管",
    purpose: "定型業務についてAIに任せる部分と人間が判断する部分を整理し、AI Operation Matrixとして確定する。",
  },
];

export const workflows: Workflow[] = [
  {
    id: "wf-01-reminder",
    categoryId: "oc-01",
    title: "イベントReminder作成（3日前 / 1日前 / 当日）",
    description:
      "対象イベントが確定した時だけ、3日前・1日前・当日のリマインドをActual Task化する。イベント終了済みなら生成しない。3日前を過ぎていても3日前分を遡って作らない。",
    steps: ["初回告知", "3日前リマインド", "1日前リマインド（3日前のコピーにしない）", "当日リマインド（開催時刻を目立たせる）"],
    aiCapability: "AI_DRAFT",
    outputType: "EVENT_REMINDER",
    requiredInputs: ["eventName", "eventDate", "startTime", "deliveryChannel"],
  },
  {
    id: "wf-02-followup",
    categoryId: "oc-02",
    title: "未移行者フォロー",
    description: "対象者を確定し、移行状況を分類したうえで、フォローが必要な人にだけ文面を作成・送信する。",
    steps: [
      "現在の対象者一覧を確定する",
      "各人をMIGRATED / NOT_MIGRATED / EXEMPT / UNKNOWNに分類する",
      "UNKNOWNを確認する",
      "NOT_MIGRATEDかつfollowupRequiredの人を確定する",
      "フォロー文面を作成する",
      "対象者×文面×送信先をセットする",
      "送信する",
      "送信後の移行確認をする",
      "statusを更新する",
    ],
    aiCapability: "AI_DRAFT",
    outputType: "MESSAGE_DRAFT",
    requiredInputs: ["対象者一覧", "各人のmigrationStatus", "previousMessageSent", "previousMessageReference/migrationLink"],
  },
  {
    id: "wf-02-migrated",
    categoryId: "oc-02",
    title: "移行済み者向け案内",
    description: "必須業務であることが確認できていないためTemplateとして保持。実際に送る必要が発生した場合のみActual Task化する。",
    steps: ["移行済み対象者を確認する", "次に案内すべき内容の有無を確認する", "あれば案内文面を作成する"],
    aiCapability: "AI_DRAFT",
    outputType: "MESSAGE_DRAFT",
    requiredInputs: ["移行済み対象者情報", "次に案内すべき内容の有無"],
  },
  {
    id: "wf-03-inquiry",
    categoryId: "oc-03",
    title: "問い合わせ対応",
    description: "問い合わせ内容を整理し、既知情報だけで回答可能か判定する。判定できなければ運営確認Taskの候補にする。",
    steps: [
      "問い合わせ内容を整理する",
      "既知情報だけで回答可能か判定する",
      "可能なら回答文を作成する",
      "不可能なら運営確認Task候補にする",
      "Self-QAする",
      "READY_TO_SENDにする",
      "Human確認後に送信する",
    ],
    aiCapability: "AI_DRAFT",
    outputType: "MESSAGE_DRAFT",
    requiredInputs: ["問い合わせ内容", "関連イベント・メンバー情報（あれば）"],
  },
  {
    id: "wf-04-check",
    categoryId: "oc-04",
    title: "運営確認",
    description: "「Slackで相談する」のような曖昧なTaskにせず、何を・なぜ・誰に確認するかを一文で具体化する。",
    steps: ["確認テーマを一文で具体化する", "なぜ必要か明確にする", "確認文をREADY_TO_SENDにする", "回答を受領する", "関連Taskへ反映する"],
    aiCapability: "AI_DRAFT",
    outputType: "MESSAGE_DRAFT",
    requiredInputs: ["question", "reason", "recipient", "context", "desiredAnswer"],
  },
  {
    id: "wf-05-monthly",
    categoryId: "oc-05",
    title: "月次状況整理 / 報告",
    description: "今月の提出期限・提出先・フォーマット・必須項目が確認できるまでActual Task化しない。",
    steps: ["reportingPeriodを確認する", "deadline・提出先・フォーマットを確認する", "必須項目を確認する", "揃った時点でActual Task化する"],
    aiCapability: "HYBRID",
    outputType: "OPERATION_DOC",
    requiredInputs: ["reportingPeriod", "deadline", "recipient", "requiredItems", "format", "destination"],
  },
  {
    id: "wf-06-post",
    categoryId: "oc-06",
    title: "定型投稿 / お知らせ",
    description: "投稿テーマ・投稿先・対象・必要情報・期限が確定していることを条件にActual Task化する。",
    steps: ["投稿テーマを確認する", "投稿先・対象を確認する", "必要情報を確認する", "文面を作成する", "Self-QAする"],
    aiCapability: "AI_DRAFT",
    outputType: "MESSAGE_DRAFT",
    requiredInputs: ["投稿テーマ", "投稿先", "対象", "必要情報", "期限"],
  },
  {
    id: "wf-07-matrix",
    categoryId: "oc-07",
    title: "AI Operation Matrix整備",
    description: "Operations Masterの主要業務についてTrigger・入力・AI Capability・Output・完了条件を定義し、candidate分類を確定させる。",
    steps: ["主要業務を洗い出す", "各業務のTrigger・入力を確認する", "AI Capabilityを判定する", "Output・保存先を整理する", "完了条件を定義する"],
    aiCapability: "HYBRID",
    outputType: "OPERATION_DOC",
    requiredInputs: [],
  },
];

// Current-work audit (2026-09-05). Nearly everything here is UNKNOWN on
// purpose: a past record of an activity is not evidence it's still active or
// that it's done now (see PRD.md 22/23) — verifying the real current state
// (who has migrated, whether a DM is still unanswered, whether an event is
// upcoming) requires checking RIALA itself, which this session cannot do.
export const operationalAudits: OperationalAudit[] = [
  {
    id: "audit-01",
    categoryId: "oc-02",
    title: "FANTS → 独自アプリ移行対応",
    currentStatus: "UNKNOWN",
    evidence: "過去に移行対応が行われていた記録はあるが、2026-09時点の対象者・進捗は未確認",
    requiredAction: "現在の対象者一覧と各人の移行状況を再監査する",
    missingInputs: ["対象メンバー一覧", "各人の現在の移行状況"],
    actualTaskId: null,
    notes: null,
  },
  {
    id: "audit-02",
    categoryId: "oc-02",
    title: "移行済み / 未移行者で案内文面を分ける対応",
    currentStatus: "UNKNOWN",
    evidence: "過去に文面を分けて対応した記録がある",
    requiredAction: "現在も同じ運用が必要か確認する",
    missingInputs: ["現在の対象者の分類状況"],
    actualTaskId: null,
    notes: null,
  },
  {
    id: "audit-03",
    categoryId: "oc-02",
    title: "FANTS内DMでの案内",
    currentStatus: "UNKNOWN",
    evidence: "過去にFANTS内DMで案内した記録がある",
    requiredAction: "現在も追加の案内が必要な対象がいるか確認する",
    missingInputs: ["送信済み対象者と内容の記録"],
    actualTaskId: null,
    notes: null,
  },
  {
    id: "audit-04",
    categoryId: "oc-02",
    title: "メールでの案内",
    currentStatus: "UNKNOWN",
    evidence: "過去にメールで案内した記録がある",
    requiredAction: "現在も追加の案内が必要な対象がいるか確認する",
    missingInputs: ["送信済み対象者と内容の記録"],
    actualTaskId: null,
    notes: null,
  },
  {
    id: "audit-05",
    categoryId: "oc-02",
    title: "一部メンバーの移行確認",
    currentStatus: "UNKNOWN",
    evidence: "一部メンバーについて移行確認を行った記録がある",
    requiredAction: "確認済みメンバーの現在状態を再確認する",
    missingInputs: ["確認済みメンバーの一覧"],
    actualTaskId: null,
    notes: null,
  },
  {
    id: "audit-06",
    categoryId: "oc-02",
    title: "紹介プラン等の特殊ケース",
    currentStatus: "UNKNOWN",
    evidence: "紹介プラン等、通常フローと異なる特殊ケースが存在した記録がある",
    requiredAction: "現在残っている特殊ケースの有無を確認する",
    missingInputs: ["特殊ケース対象者の現在状況"],
    actualTaskId: null,
    notes: null,
  },
  {
    id: "audit-07",
    categoryId: "oc-01",
    title: "イベント告知",
    currentStatus: "UNKNOWN",
    evidence: "過去にイベント告知を行った記録がある",
    requiredAction: "今後予定されているイベントの有無を確認する",
    missingInputs: ["今後のイベント予定"],
    actualTaskId: null,
    notes: null,
  },
  {
    id: "audit-08",
    categoryId: "oc-01",
    title: "イベント参加方法の案内",
    currentStatus: "UNKNOWN",
    evidence: "過去に参加方法を案内した記録がある",
    requiredAction: "現在案内が必要なイベントがあるか確認する",
    missingInputs: ["今後のイベント予定"],
    actualTaskId: null,
    notes: null,
  },
  {
    id: "audit-09",
    categoryId: "oc-01",
    title: "イベントリマインド",
    currentStatus: "UNKNOWN",
    evidence: "直近で確認できているイベントは2026-09-03開催分のみで、既に終了している",
    requiredAction: "次に予定されているイベントの有無を確認する",
    missingInputs: ["今後のイベント予定"],
    actualTaskId: null,
    notes: "対象イベントが確定するまでReminder Actual Taskは生成しない",
  },
  {
    id: "audit-10",
    categoryId: "oc-03",
    title: "DM / 問い合わせ対応",
    currentStatus: "UNKNOWN",
    evidence: "過去にDM・問い合わせ対応を行った記録がある",
    requiredAction: "現在未返信のDM・問い合わせがあるか確認する",
    missingInputs: ["未返信DM・問い合わせの一覧"],
    actualTaskId: null,
    notes: null,
  },
  {
    id: "audit-11",
    categoryId: "oc-04",
    title: "運営側への確認",
    currentStatus: "UNKNOWN",
    evidence: "過去に運営側へ確認を行った記録がある",
    requiredAction: "現在確認待ちの事項があるか確認する",
    missingInputs: ["確認待ち事項の一覧"],
    actualTaskId: null,
    notes: null,
  },
  {
    id: "audit-12",
    categoryId: "oc-05",
    title: "DM結果 / 移行状況等の月次整理",
    currentStatus: "UNKNOWN",
    evidence: "過去に月次整理を行った記録がある",
    requiredAction: "今月の提出期限・提出先・フォーマットを確認する",
    missingInputs: ["reportingPeriod", "deadline", "recipient", "format"],
    actualTaskId: null,
    notes: null,
  },
  {
    id: "audit-13",
    categoryId: "oc-06",
    title: "投稿文面作成",
    currentStatus: "UNKNOWN",
    evidence: "過去に投稿文面を作成した記録がある",
    requiredAction: "現在作成が必要な投稿があるか確認する",
    missingInputs: ["投稿テーマ・投稿先・期限"],
    actualTaskId: null,
    notes: null,
  },
  {
    id: "audit-14",
    categoryId: "oc-01",
    title: "2026-09-03「AIを使った海外向けビジネス構築」oViceイベント",
    currentStatus: "DONE",
    evidence: "開催日が2026-09-03のため、2026-09-05時点で開催済み",
    requiredAction: null,
    missingInputs: [],
    actualTaskId: null,
    notes: "過去イベントのため3日前・1日前・当日リマインドは作成しない。関連する投稿作業自体が完了しているかは個別未確認",
  },
  {
    id: "audit-15",
    categoryId: "oc-07",
    title: "RIALA定型業務のAI移管設計",
    currentStatus: "ACTIVE",
    evidence: "Actual Task「RIALA定型業務のAI移管範囲を確定する」として進行中",
    requiredAction: null,
    missingInputs: [],
    actualTaskId: "t-riala-007",
    notes: "Operation Matrixが完成した時点でDONEへ更新する",
  },
];

// Candidate handoff mapping (section 16) — not confirmed. automationStatus
// stays CANDIDATE until the AI移管 task above actually confirms it.
export const aiOperationMatrix: AiOperationMatrixEntry[] = [
  {
    id: "matrix-01",
    operation: "イベント投稿文作成",
    categoryId: "oc-01",
    frequency: null,
    trigger: "イベントが確定した時",
    requiredInputs: ["eventName", "eventDate", "startTime", "deliveryChannel"],
    aiCapability: "AI_DRAFT",
    aiProcess: ["情報整理", "文面作成", "Self-QA"],
    humanAction: ["最終確認", "投稿"],
    outputType: "EVENT_REMINDER",
    outputDestination: null,
    completionCondition: "READY_TO_SENDになっている",
    automationStatus: "CANDIDATE",
    missingInputs: [],
  },
  {
    id: "matrix-02",
    operation: "イベント情報QA",
    categoryId: "oc-01",
    frequency: null,
    trigger: "リマインド作成時",
    requiredInputs: ["イベント情報一式"],
    aiCapability: "AI_EXECUTE",
    aiProcess: ["必要項目の抜け漏れチェック", "誤字脱字チェック"],
    humanAction: [],
    outputType: null,
    outputDestination: null,
    completionCondition: "抜け漏れ・誤字がない状態",
    automationStatus: "CANDIDATE",
    missingInputs: [],
  },
  {
    id: "matrix-03",
    operation: "イベント実投稿",
    categoryId: "oc-01",
    frequency: null,
    trigger: "文面がREADY_TO_SENDになった時",
    requiredInputs: ["外部送信・投稿権限"],
    aiCapability: "HUMAN",
    aiProcess: [],
    humanAction: ["投稿する"],
    outputType: null,
    outputDestination: null,
    completionCondition: "投稿完了",
    automationStatus: "CANDIDATE",
    missingInputs: ["外部送信権限の確認"],
  },
  {
    id: "matrix-04",
    operation: "移行状況整理",
    categoryId: "oc-02",
    frequency: null,
    trigger: "対象メンバー一覧が確定した時",
    requiredInputs: ["対象メンバー一覧", "現在の移行状況データ"],
    aiCapability: "AI_EXECUTE",
    aiProcess: ["ステータス分類", "抜け漏れチェック"],
    humanAction: ["UNKNOWNの確認"],
    outputType: "MEMBER_STATUS_LIST",
    outputDestination: null,
    completionCondition: "全対象者にステータスが付いている",
    automationStatus: "CANDIDATE",
    missingInputs: ["対象メンバー一覧", "現在の移行状況データ"],
  },
  {
    id: "matrix-05",
    operation: "未移行者文面",
    categoryId: "oc-02",
    frequency: null,
    trigger: "NOT_MIGRATEDかつfollowupRequiredの対象が確定した時",
    requiredInputs: ["対象者", "previousMessageReference/migrationLink"],
    aiCapability: "AI_DRAFT",
    aiProcess: ["文面作成", "Self-QA"],
    humanAction: ["最終確認", "送信"],
    outputType: "MESSAGE_DRAFT",
    outputDestination: null,
    completionCondition: "READY_TO_SENDになっている",
    automationStatus: "CANDIDATE",
    missingInputs: [],
  },
  {
    id: "matrix-06",
    operation: "DM回答案",
    categoryId: "oc-03",
    frequency: null,
    trigger: "問い合わせ受領時",
    requiredInputs: ["問い合わせ内容"],
    aiCapability: "AI_DRAFT",
    aiProcess: ["内容整理", "回答文作成", "Self-QA"],
    humanAction: ["最終確認", "送信"],
    outputType: "MESSAGE_DRAFT",
    outputDestination: null,
    completionCondition: "READY_TO_SENDになっている",
    automationStatus: "CANDIDATE",
    missingInputs: [],
  },
  {
    id: "matrix-07",
    operation: "運営方針変更",
    categoryId: "oc-04",
    frequency: null,
    trigger: "方針判断が必要になった時",
    requiredInputs: [],
    aiCapability: "DECISION",
    aiProcess: ["案の提示"],
    humanAction: ["最終判断"],
    outputType: null,
    outputDestination: null,
    completionCondition: "人間が判断した",
    automationStatus: "NOT_APPLICABLE",
    missingInputs: [],
  },
  {
    id: "matrix-08",
    operation: "不明状態確認",
    categoryId: "oc-04",
    frequency: null,
    trigger: "UNKNOWN状態の項目が見つかった時",
    requiredInputs: [],
    aiCapability: "HYBRID",
    aiProcess: ["確認テーマの具体化", "確認文の作成"],
    humanAction: ["確認先への送信", "回答受領後の反映"],
    outputType: "MESSAGE_DRAFT",
    outputDestination: null,
    completionCondition: "UNKNOWNが解消された",
    automationStatus: "CANDIDATE",
    missingInputs: [],
  },
];
