"use client";
import { useState } from "react";
import Link from "next/link";
import { useWork } from "@/lib/work/client";
import { useTodayExecution } from "@/lib/todayExecutionStore";
import { addDaysToYmd, formatMd } from "@/lib/date";
import { buildDailyReview, buildWeeklyReview, CONFIDENCE_LABEL } from "@/lib/pdca";
import { varianceReasonLabel } from "@/lib/execution";
import StudioHeader from "@/components/StudioHeader";
import StudioConnection from "@/components/StudioConnection";
import TaskDetailSheet from "@/components/TaskDetailSheet";
export default function ReviewPage() {
  const work=useWork(); const store=useTodayExecution(); const [period,setPeriod]=useState("1日"); const [chosenDate,setChosenDate]=useState(""); const [selectedId,setSelectedId]=useState<string|null>(null);
  const date=chosenDate || store.currentDate; const from=period==="1日"?date:addDaysToYmd(date,-6);
  const daily=buildDailyReview({date,tasks:work.tasks,allTasks:work.tasks,completions:store.completions,varianceReasons:store.varianceReasonByTaskId,replanFlags:store.replanFlags,dispositions:store.dispositions});
  const weekly=buildWeeklyReview(from,date,work.tasks,store.completions,store.varianceReasonByTaskId,store.replanFlags);
  const records=Object.values(store.completions).filter(r=>r.completedOnDate>=from && r.completedOnDate<=date);
  const completed=records.filter(r=>r.metDefinitionOfDone).length; const actuals=records.filter(r=>r.actualMinutes!==null); const actual=actuals.reduce((sum,r)=>sum+(r.actualMinutes??0),0);
  const checks=period==="1日"?[...daily.over,...daily.under]:[];
  const suggestions=weekly.groups.filter(g=>g.samples.length>=3 && g.averageDriftMinutes!==null && Math.abs(g.averageDriftMinutes)>=15).slice(0,3);
  const selected=work.tasks.find(t=>t.id===selectedId);
  return <div className="studio"><StudioHeader title="ひと息、振り返り" subtitle="できたことを残して、次を少しやりやすく。" kind="review" action={<Link href="/today" className="studio-secondary">今日の作業へ →</Link>} />
    <div className="studio-toolbar"><div className="studio-tabs" aria-label="振り返り期間">{["1日","7日間"].map(x=><button key={x} aria-pressed={period===x} onClick={()=>setPeriod(x)}>{x}</button>)}</div><label className="flex items-center gap-3 text-sm text-[#756b85]">{period==="1日"?"日付":"終了日"}<input aria-label="振り返る日" type="date" className="rounded-xl border border-[#e4dfed] bg-white px-3 py-2" max={store.currentDate} value={date} onChange={e=>setChosenDate(e.target.value)} /></label><span className="text-xs text-[#877e94]">{formatMd(from)}{from!==date && "〜"+formatMd(date)}</span></div>
    <div className="mb-7 grid grid-cols-3 gap-3"><Stat label="完了したこと" value={work.connected && store.executionReady?String(completed):"—"} unit="件" /><Stat label="記録した時間" value={work.connected && store.executionReady && actuals.length?String(actual):"—"} unit="分" /><Stat label="時間の未入力" value={work.connected && store.executionReady?String(records.length-actuals.length):"—"} unit="件" /></div>
    <div className="grid gap-6 lg:grid-cols-[1.2fr_1fr]"><section className="studio-card p-5 sm:p-6"><h2 className="mb-5 text-base font-semibold text-[#3b334b]">この期間に終えたこと</h2>{records.length===0 ? <div className="studio-empty !min-h-48"><span className="text-3xl text-[#bbafd5]" aria-hidden="true">⌁</span><p className="font-semibold">まだ、実行の記録はありません</p><p>タスクを終えると、ここに振り返りが残ります。</p><Link href="/tasks" className="studio-secondary">やることを見る</Link></div> : <ul className="space-y-3">{records.map(r=>{const t=work.tasks.find(t=>t.id===r.taskId);return <li key={r.taskId}><button className="w-full rounded-2xl bg-[#f8f6fb] p-4 text-left" onClick={()=>setSelectedId(r.taskId)} disabled={!t}><div className="flex items-start gap-3"><span aria-hidden="true" className={r.metDefinitionOfDone?"text-[#659882]":"text-[#b48d56]"}>{r.metDefinitionOfDone?"✓":"○"}</span><div><p className="text-sm font-medium leading-7">{t?.title ?? "関連タスクが見つかりません"}</p><p className="mt-1 text-xs leading-6 text-[#877e94]">{formatMd(r.completedOnDate)}・{r.metDefinitionOfDone?"完了条件を満たして完了":"完了条件は未確認"}・{r.actualMinutes===null?"実績時間は未入力":r.actualMinutes+"分"}</p></div></div></button></li>;})}</ul>}</section>
    <section className="studio-card p-5 sm:p-6"><h2 className="mb-5 text-base font-semibold text-[#3b334b]">次に変えること</h2>{period==="1日" ? checks.length===0 ? <p className="rounded-2xl bg-[#f3f7f4] p-5 text-sm leading-8 text-[#657a6c]">{records.length===0?"実績がたまったら、見積りと実際の時間を比べてみましょう。":records.length>actuals.length?"時間が未入力のタスクがあります。記録を足してから、見積りを見直しましょう。":"記録した範囲では、大きな時間のずれはありません。"}</p> : <ul className="space-y-4">{checks.map(item=><li key={item.task.id} className="rounded-2xl bg-[#f8f6fb] p-4"><button className="text-left text-sm font-medium leading-7" onClick={()=>setSelectedId(item.task.id)}>{item.task.title}</button><p className="mt-2 text-xs leading-7 text-[#877e94]">見積り {item.estimateMinutes}分 → 実績 {item.actualMinutes}分</p>{item.reason && <p className="mt-1 text-xs leading-7 text-[#756b85]">{varianceReasonLabel[item.reason]}</p>}{item.proposal && item.proposal.samples.length>=3 && <button disabled={!work.connected || !store.executionReady} className="studio-secondary mt-3" onClick={()=>store.setNextEstimate(item.task.id,item.proposal!.suggestedMinutes)}>{store.nextEstimates[item.task.id]===item.proposal.suggestedMinutes?"次回見積りに採用済み":"次回の見積りを"+item.proposal.suggestedMinutes+"分に"}</button>}</li>)}</ul> : suggestions.length===0 ? <p className="rounded-2xl bg-[#f3f7f4] p-5 text-sm leading-8 text-[#657a6c]">同じ種類の実績が3件以上たまると、次の見積り候補を確認できます。</p> : <ul className="space-y-4">{suggestions.map(g=><li key={g.groupKey} className="rounded-2xl bg-[#f8f6fb] p-4"><p className="text-sm font-medium leading-7">{g.groupLabel}</p><p className="mt-2 text-sm text-[#6a5889]">次回候補 {g.suggestedMinutes}分</p><p className="mt-2 text-xs leading-7 text-[#877e94]">実績 {g.samples.join("・")}分 / {CONFIDENCE_LABEL[g.confidence]}</p></li>)}</ul>}
      <Link href="/pdca/analysis" className="mt-6 inline-block min-h-11 py-3 text-xs text-[#69548c]">時間の比較・再計画を詳しく見る →</Link>
    </section></div><p className="mt-5 text-xs leading-6 text-[#877e94]">実績未入力は0分と数えません。見積りを採用しても、Calendarの予定は自動で変わりません。</p>
    <div className="mt-8 border-t border-[#eeeaf3] pt-6"><StudioConnection /></div>
    {selected && <TaskDetailSheet key={selected.id} task={selected} onClose={()=>setSelectedId(null)} onNavigateToTask={setSelectedId} />}
  </div>;
}
function Stat({label,value,unit}:{label:string;value:string;unit:string}) {return <div className="studio-card p-4 sm:p-6"><p className="text-xs leading-6 text-[#877e94]">{label}</p><p className="mt-2 text-2xl font-semibold tabular-nums text-[#4c405f] sm:text-3xl">{value}<span className="ml-1 text-xs font-normal">{unit}</span></p></div>;}
